// frontend/src/app/components/episodios/episodio-list/episodio-list.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router, ActivatedRoute } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { EpisodioService } from '../../../services/episodio.service';
import { TemporadaService } from '../../../services/temporada.service';
import { SharedService } from '../../../services/shared.service';
import { Episodio, Temporada } from '../../../models/interfaces';

@Component({
  selector: 'app-episodio-list',
  standalone: true,
  templateUrl: './episodio-list.component.html',
  styleUrls: ['./episodio-list.component.css'],
  imports: [CommonModule, RouterModule, FormsModule]
})
export class EpisodioListComponent implements OnInit {
  episodios: Episodio[] = [];
  episodiosFiltrados: Episodio[] = [];
  episodiosPaginados: Episodio[] = [];
  temporadas: Temporada[] = [];
  searchTerm = '';
  filtroTemporada = '';
  
  currentPage = 1;
  itemsPerPage = 10;
  totalPages = 1;
  Math = Math;

  constructor(
    private episodioService: EpisodioService,
    private temporadaService: TemporadaService,
    private sharedService: SharedService,
    private router: Router,
    private route: ActivatedRoute,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit() {
    console.log('🎬 Iniciando EpisodioListComponent...');
    this.cargarTemporadas();
    this.cargarEpisodios();
    
    // Leer parámetro de temporada de la URL
    this.route.queryParams.subscribe(params => {
      if (params['temporada']) {
        this.filtroTemporada = params['temporada'];
        this.aplicarFiltros();
      }
    });
  }

  cargarTemporadas() {
    this.temporadaService.getAll().subscribe({
      next: (response) => {
        if (response.success && response.data) {
          this.temporadas = response.data;
        }
      },
      error: (error) => {
        console.error('❌ Error al cargar temporadas:', error);
      }
    });
  }

  cargarEpisodios() {
    console.log('🔄 Cargando episodios desde API...');
    this.sharedService.showLoading();
    this.episodioService.getAll().subscribe({
      next: (response) => {
        console.log('✅ Respuesta recibida:', response);
        console.log('🔄 Llamando a hideLoading()...');
        this.sharedService.hideLoading();
        if (response.success && response.data) {
          console.log(`✅ ${response.data.length} episodios cargados`);
          this.episodios = response.data;
          this.aplicarFiltros();
        } else {
          console.warn('⚠️ Respuesta sin datos válidos:', response);
        }
      },
      error: (error) => {
        console.error('❌ Error al cargar episodios:', error);
        this.sharedService.hideLoading();
        this.sharedService.showError('Error al cargar episodios');
      }
    });
  }

  aplicarFiltros() {
    console.log('🔍 Aplicando filtros. Total episodios:', this.episodios.length);
    let filtered = [...this.episodios];

    if (this.searchTerm) {
      const term = this.searchTerm.toLowerCase();
      filtered = filtered.filter(e => 
        e.titulo.toLowerCase().includes(term) ||
        e.descripcion.toLowerCase().includes(term)
      );
    }

    if (this.filtroTemporada) {
      filtered = filtered.filter(e => {
        const tempId = typeof e.temporada_id === 'object' && e.temporada_id !== null 
          ? (e.temporada_id as any)._id 
          : e.temporada_id;
        return tempId === this.filtroTemporada;
      });
    }

    this.episodiosFiltrados = filtered;
    this.totalPages = Math.ceil(this.episodiosFiltrados.length / this.itemsPerPage);
    this.currentPage = 1;
    console.log('✅ Episodios filtrados:', this.episodiosFiltrados.length, 'Total páginas:', this.totalPages);
    console.log('📋 Array episodiosFiltrados:', this.episodiosFiltrados);
    
    // Actualizar paginación en el siguiente ciclo para evitar ExpressionChangedAfterItHasBeenCheckedError
    setTimeout(() => this.actualizarPaginacion(), 0);
  }

  actualizarPaginacion() {
    const start = (this.currentPage - 1) * this.itemsPerPage;
    const end = start + this.itemsPerPage;
    this.episodiosPaginados = this.episodiosFiltrados.slice(start, end);
    this.cdr.detectChanges();
    console.log(`📄 Página ${this.currentPage}: mostrando ${this.episodiosPaginados.length} episodios (${start}-${end})`);
  }

  cambiarPagina(page: number) {
    if (page >= 1 && page <= this.totalPages) {
      this.currentPage = page;
      this.actualizarPaginacion();
    }
  }

  verDetalle(id: string) {
    this.router.navigate(['/episodios', id]);
  }

  eliminar(episodio: Episodio) {
    if (!episodio._id) return;

    if (confirm(`¿Estás seguro de eliminar "${episodio.titulo}"?`)) {
      this.sharedService.showLoading();
      this.episodioService.delete(episodio._id).subscribe({
        next: (response) => {
          this.sharedService.hideLoading();
          if (response.success) {
            this.sharedService.showSuccess('Episodio eliminado correctamente');
            this.cargarEpisodios();
          }
        },
        error: (error) => {
          this.sharedService.hideLoading();
          this.sharedService.showError('Error al eliminar episodio');
          console.error(error);
        }
      });
    }
  }

  getTemporadaTitulo(temporada: any): string {
    return temporada?.titulo || 'Temporada ' + temporada?.numero_temporada || 'N/A';
  }

  limpiarFiltros() {
    this.searchTerm = '';
    this.filtroTemporada = '';
    this.router.navigate([], {
      relativeTo: this.route,
      queryParams: {},
    });
    this.aplicarFiltros();
  }

  getImagenEpisodio(episodio: Episodio): string {
    if (episodio.imagen_url) {
      return episodio.imagen_url;
    }
    
    // Obtener el número de temporada del episodio
    let numeroTemporada = 1;
    if (typeof episodio.temporada_id === 'object' && episodio.temporada_id !== null) {
      numeroTemporada = (episodio.temporada_id as any).numero_temporada || 1;
    }
    
    return `https://picsum.photos/seed/spyxfamily-t${numeroTemporada}e${episodio.numero_episodio}/400/250`;
  }

  onImageError(event: any): void {
    event.target.src = 'https://via.placeholder.com/400x250/6c757d/ffffff?text=Episodio';
  }
}

<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2>🎬 Episodios</h2>
  </div>

  <!-- Filtros -->
  <div class="card mb-4">
    <div class="card-body">
      <div class="row g-3">
        <div class="col-md-6">
          <label class="form-label">Buscar</label>
          <input 
            type="text" 
            class="form-control" 
            placeholder="Buscar por título o descripción..."
            [(ngModel)]="searchTerm"
            (ngModelChange)="aplicarFiltros()">
        </div>
        <div class="col-md-4">
          <label class="form-label">Filtrar por Temporada</label>
          <select
            class="form-select"
            [(ngModel)]="filtroTemporada"
            (ngModelChange)="aplicarFiltros()">
            <option value="">Todas las temporadas</option>
            <option *ngFor="let temporada of temporadas" [value]="temporada._id">
              Temporada {{ temporada.numero_temporada }}: {{ temporada.titulo }}
            </option>
          </select>
        </div>
        <div class="col-md-2 d-flex align-items-end">
          <button class="btn btn-secondary w-100" (click)="limpiarFiltros()">
            Limpiar
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Grid de Tarjetas de Episodios -->
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 mb-4">
    <div class="col" *ngFor="let episodio of episodiosPaginados">
      <div class="card h-100">
        <img 
          [src]="getImagenEpisodio(episodio)" 
          class="card-img-top" 
          [alt]="episodio.titulo"
          style="height: 200px; object-fit: cover; cursor: pointer;"
          (error)="onImageError($event)"
          (click)="verDetalle(episodio._id!)">
        <div class="card-body">
          <span class="badge bg-primary mb-2">EP {{ episodio.numero_episodio }}</span>
          <h5 class="card-title">{{ episodio.titulo }}</h5>
          <p class="card-text small">{{ episodio.descripcion | slice:0:100 }}{{ episodio.descripcion.length > 100 ? '...' : '' }}</p>
          <div class="small text-muted">
            <div><strong>Duración:</strong> {{ episodio.duracion_minutos }} min</div>
            <div><strong>Emisión:</strong> {{ episodio.fecha_emision | date:'dd/MM/yyyy' }}</div>
            <div *ngIf="episodio.valoracion"><strong>⭐ Valoración:</strong> {{ episodio.valoracion }}/10</div>
          </div>
        </div>
        <div class="card-footer bg-transparent">
          <button 
            class="btn btn-sm btn-info w-100" 
            (click)="verDetalle(episodio._id!)"
            title="Ver detalle">
            <i class="bi bi-eye"></i> Ver Detalle
          </button>
        </div>
      </div>
    </div>
    
    <div class="col-12" *ngIf="episodiosPaginados.length === 0">
      <div class="alert alert-info text-center">
        No se encontraron episodios
      </div>
    </div>
  </div>

      <!-- Paginación -->
      <nav *ngIf="totalPages > 1">
        <ul class="pagination justify-content-center">
          <li class="page-item" [class.disabled]="currentPage === 1">
            <button class="page-link" (click)="cambiarPagina(currentPage - 1)">
              Anterior
            </button>
          </li>
          <li 
            class="page-item" 
            *ngFor="let page of [].constructor(totalPages); let i = index"
            [class.active]="currentPage === i + 1">
            <button class="page-link" (click)="cambiarPagina(i + 1)">
              {{ i + 1 }}
            </button>
          </li>
          <li class="page-item" [class.disabled]="currentPage === totalPages">
            <button class="page-link" (click)="cambiarPagina(currentPage + 1)">
              Siguiente
            </button>
          </li>
  <!-- Paginación -->
  <nav *ngIf="totalPages > 1" class="pagination-container">
    <ul class="pagination justify-content-center">
      <li class="page-item" [class.disabled]="currentPage === 1">
        <button class="page-link" (click)="cambiarPagina(currentPage - 1)">
          Anterior
        </button>
      </li>
      <li 
        class="page-item" 
v>

// frontend-react/src/components/episodios/EpisodioList.js
import React, { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import './EpisodioList.css';
import episodioService from '../../services/episodioService';
import temporadaService from '../../services/temporadaService';
import Loading from '../Loading';

const EpisodioList = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const [episodios, setEpisodios] = useState([]);
  const [temporadas, setTemporadas] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [filtroTemporada, setFiltroTemporada] = useState(searchParams.get('temporada') || '');

  useEffect(() => {
    cargarDatos();
  }, []);

  useEffect(() => {
    const temporadaParam = searchParams.get('temporada');
    if (temporadaParam) {
      setFiltroTemporada(temporadaParam);
    }
  }, [searchParams]);

  const cargarDatos = async () => {
    try {
      setLoading(true);
      setError(null);
      
      // Cargar temporadas y episodios en paralelo
      const [episodiosData, temporadasData] = await Promise.all([
        episodioService.getAll(),
        temporadaService.getAll()
      ]);
      
      console.log('Episodios cargados:', episodiosData);
      console.log('Temporadas cargadas:', temporadasData);
      
      setEpisodios(episodiosData);
      setTemporadas(temporadasData);
    } catch (err) {
      setError('Error al cargar los datos: ' + err.message);
      console.error('Error:', err);
    } finally {
      setLoading(false);
    }
  };

  const obtenerNumeroTemporada = (temporadaId) => {
    // Si el backend hizo populate, temporadaId es un objeto con los datos
    if (typeof temporadaId === 'object' && temporadaId !== null) {
      return temporadaId.numero_temporada;
    }
    // Si no, buscar en el array de temporadas
    const temporada = temporadas.find(t => t._id === temporadaId);
    return temporada ? temporada.numero_temporada : 1;
  };

  const obtenerNombreTemporada = (temporadaId) => {
    // Si el backend hizo populate, temporadaId es un objeto con los datos
    if (typeof temporadaId === 'object' && temporadaId !== null) {
      return `Temporada ${temporadaId.numero_temporada}: ${temporadaId.titulo}`;
    }
    // Si no, buscar en el array de temporadas
    const temporada = temporadas.find(t => t._id === temporadaId);
    return temporada ? `Temporada ${temporada.numero_temporada}: ${temporada.titulo}` : 'Temporada desconocida';
  };

  // Función para obtener imagen del episodio
  const getImagenEpisodio = (episodio) => {
    // Si el episodio tiene imagen_url, usarla
    if (episodio.imagen_url) {
      return episodio.imagen_url;
    }
    
    // Si no tiene imagen, usar una por defecto basada en temporada y episodio
    const numeroTemp = obtenerNumeroTemporada(episodio.temporada_id);
    const numeroEp = episodio.numero_episodio;
    return `https://picsum.photos/seed/spyxfamily-default-t${numeroTemp}e${numeroEp}/400/250`;
  };

  // Manejar error de carga de imagen
  const handleImageError = (e, episodio) => {
    const numeroTemp = obtenerNumeroTemporada(episodio.temporada_id);
    const numeroEp = episodio.numero_episodio;
    
    // Fallback a otra URL de picsum con seed diferente
    e.target.src = `https://picsum.photos/seed/fallback-spyxfamily-t${numeroTemp}e${numeroEp}/400/250`;
  };

  const filtrarEpisodios = () => {
    if (!filtroTemporada) {
      return episodios;
    }
    return episodios.filter(ep => {
      // El backend hace populate, entonces temporada_id puede ser un objeto o un string
      const tempId = typeof ep.temporada_id === 'object' ? ep.temporada_id._id : ep.temporada_id;
      return tempId === filtroTemporada;
    });
  };

  const formatearFecha = (fecha) => {
    const date = new Date(fecha);
    return date.toLocaleDateString('es-ES', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
  };

  if (loading) return <Loading />;

  if (error) {
    return (
      <div className="container mt-4">
        <div className="alert alert-danger" role="alert">
          {error}
        </div>
      </div>
    );
  }

  const episodiosFiltrados = filtrarEpisodios();

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h2>🎬 Episodios de Spy×Family</h2>
      </div>

      {/* Filtros */}
      <div className="card mb-4">
        <div className="card-body">
          <div className="row">
            <div className="col-md-12">
              <label className="form-label fw-bold">Filtrar por Temporada:</label>
              <select 
                className="form-select" 
                value={filtroTemporada}
                onChange={(e) => {
                  const value = e.target.value;
                  setFiltroTemporada(value);
                  if (value) {
                    setSearchParams({ temporada: value });
                  } else {
                    setSearchParams({});
                  }
                }}
              >
                <option value="">Todas las temporadas</option>
                {temporadas.map(temporada => (
                  <option key={temporada._id} value={temporada._id}>
                    Temporada {temporada.numero_temporada}: {temporada.titulo}
                  </option>
                ))}
              </select>
            </div>
          </div>
        </div>
      </div>

      {/* Resultados */}
      <div className="mb-3">
        <span className="badge bg-primary">
          {episodiosFiltrados.length} episodio{episodiosFiltrados.length !== 1 ? 's' : ''} encontrado{episodiosFiltrados.length !== 1 ? 's' : ''}
        </span>
      </div>

      {/* Lista de episodios */}
      {episodiosFiltrados.length === 0 ? (
        <div className="alert alert-info">
          No se encontraron episodios con los filtros seleccionados.
        </div>
      ) : (
        <div className="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
          {episodiosFiltrados.map((episodio) => (
            <div key={episodio._id} className="col">
              <div className="card h-100 episodio-card">
                <img
                  src={getImagenEpisodio(episodio)}
                  className="card-img-top"
                  alt={episodio.titulo}
                  style={{ height: '200px', objectFit: 'cover' }}
                  onError={(e) => handleImageError(e, episodio)}
                />
                <div className="card-body">
                  <div className="d-flex justify-content-between align-items-start mb-2">
                    <span className="badge bg-secondary">
                      Temporada {obtenerNumeroTemporada(episodio.temporada_id)} Episodio {episodio.numero_episodio}
                    </span>
                    <span className="badge bg-info">
                      <i className="bi bi-clock"></i> {episodio.duracion_minutos} min
                    </span>
                  </div>
                  
                  <h5 className="card-title">{episodio.titulo}</h5>
                  
                  <p className="card-text sinopsis">
                    {episodio.descripcion}
                  </p>
                </div>
                <div className="card-footer bg-white border-top">
                  <small className="text-muted">
                    <i className="bi bi-calendar3"></i> {formatearFecha(episodio.fecha_emision)}
                  </small>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default EpisodioList;
