// frontend/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true,
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
  imports: [CommonModule, RouterModule]
})
export class NavbarComponent {
  isCollapsed = true;
  isDropdownOpen = false;

  constructor(private router: Router) {}

  toggleNavbar() {
    this.isCollapsed = !this.isCollapsed;
  }

  toggleDropdown() {
    this.isDropdownOpen = !this.isDropdownOpen;
  }
}

<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
  <div class="container">
    <a class="navbar-brand" routerLink="/">
      <strong>🕵️ Spy x Family</strong>
    </a>
    <button class="navbar-toggler" type="button" (click)="toggleNavbar()">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" [class.show]="!isCollapsed">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">
            📚 Documentación API
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink="/home" routerLinkActive="active">
            🏠 Estadísticas
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" (click)="toggleDropdown()">
            📊 Entidades
          </a>
          <ul class="dropdown-menu" [class.show]="isDropdownOpen" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" routerLink="/personajes">👥 Personajes</a></li>
            <li><a class="dropdown-item" routerLink="/temporadas">📺 Temporadas</a></li>
            <li><a class="dropdown-item" routerLink="/episodios">🎬 Episodios</a></li>
            <li><a class="dropdown-item" routerLink="/tomos">📖 Tomos</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

// frontend-react/src/components/Navbar.js
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import './Navbar.css';

const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);

  const toggleNavbar = () => {
    setIsOpen(!isOpen);
  };

  const closeNavbar = () => {
    setIsOpen(false);
  };

  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
      <div className="container-fluid">
        <Link className="navbar-brand" to="/" onClick={closeNavbar}>
          🕵️ Spy x Family API
        </Link>
        <button
          className="navbar-toggler"
          type="button"
          onClick={toggleNavbar}
          aria-controls="navbarNav"
          aria-expanded={isOpen}
          aria-label="Toggle navigation"
        >
          <span className="navbar-toggler-icon"></span>
        </button>
        <div className={`collapse navbar-collapse ${isOpen ? 'show' : ''}`} id="navbarNav">
          <ul className="navbar-nav ms-auto">
            <li className="nav-item">
              <Link className="nav-link" to="/" onClick={closeNavbar}>
                Home
              </Link>
            </li>
            <li className="nav-item">
              <Link className="nav-link" to="/temporadas" onClick={closeNavbar}>
                📺 Temporadas
              </Link>
            </li>
            <li className="nav-item">
              <Link className="nav-link" to="/episodios" onClick={closeNavbar}>
                🎬 Episodios
              </Link>
            </li>
            <li className="nav-item">
              <Link className="nav-link" to="/personajes" onClick={closeNavbar}>
                👥 Personajes
              </Link>
            </li>
            <li className="nav-item">
              <Link className="nav-link" to="/tomos" onClick={closeNavbar}>
                📖 Tomos
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;
