// frontend-react/src/components/personajes/PersonajeDetail.js
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import personajeService from '../../services/personajeService';
import Loading from '../Loading';
import './PersonajeDetail.css';

const PersonajeDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [personaje, setPersonaje] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    cargarPersonaje();
  }, [id]);

  const cargarPersonaje = async () => {
    try {
      setLoading(true);
      const data = await personajeService.getById(id);
      setPersonaje(data);
    } catch (err) {
      setError('Error al cargar el personaje: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const getImagenPersonaje = (personaje) => {
    if (personaje.imagen_url) {
      return personaje.imagen_url;
    }
    return `https://picsum.photos/seed/spyxfamily-${personaje.nombre.replace(/\s+/g, '')}/400/500`;
  };

  const handleImageError = (e) => {
    e.target.src = 'https://via.placeholder.com/400x500/6c757d/ffffff?text=Personaje';
  };

  const getRolBadgeClass = (rol) => {
    const rolClasses = {
      'principal': 'bg-danger',
      'secundario': 'bg-warning',
      'recurrente': 'bg-info',
      'invitado': 'bg-secondary'
    };
    return rolClasses[rol?.toLowerCase()] || 'bg-secondary';
  };

  if (loading) return <Loading />;
  if (error) return <div className="alert alert-danger container mt-4">{error}</div>;
  if (!personaje) return <div className="alert alert-warning container mt-4">Personaje no encontrado</div>;

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h2>👤 Detalle del Personaje</h2>
        <Link to="/personajes" className="btn btn-secondary">
          ← Volver
        </Link>
      </div>

      <div className="row">
        {/* Columna de la imagen */}
        <div className="col-md-4">
          <div className="personaje-detail-image-container">
            <img
              src={getImagenPersonaje(personaje)}
              className="img-fluid personaje-detail-image"
              alt={personaje.nombre}
              onError={handleImageError}
            />
            <div className="personaje-rol-badge">
              <span className={`badge ${getRolBadgeClass(personaje.rol)}`}>
                {personaje.rol || 'N/A'}
              </span>
            </div>
          </div>
        </div>

        {/* Columna de la información */}
        <div className="col-md-8">
          <div className="card h-100">
            <div className="card-body">
              {/* Nombre y alias */}
              <div className="personaje-header mb-4">
                <h3 className="personaje-nombre">{personaje.nombre}</h3>
                {personaje.alias && (
                  <p className="personaje-alias">
                    <span className="badge bg-secondary">{personaje.alias}</span>
                  </p>
                )}
              </div>

              {/* Información básica */}
              <div className="personaje-info-section mb-4">
                <h5 className="text-primary mb-3">🔍 Información Básica</h5>
                <div className="info-grid">
                  {personaje.edad && (
                    <div className="info-item">
                      <span className="info-label">Edad:</span>
                      <span className="info-value">{personaje.edad} años</span>
                    </div>
                  )}
                  {personaje.organizacion && (
                    <div className="info-item">
                      <span className="info-label">Organización:</span>
                      <span className="info-value badge bg-primary">{personaje.organizacion}</span>
                    </div>
                  )}
                  <div className="info-item">
                    <span className="info-label">Rol:</span>
                    <span className={`info-value badge ${getRolBadgeClass(personaje.rol)}`}>
                      {personaje.rol || 'No especificado'}
                    </span>
                  </div>
                </div>
              </div>

              {/* Descripción */}
              <div className="personaje-info-section mb-4">
                <h5 className="text-secondary mb-3">📖 Descripción</h5>
                <p className="personaje-descripcion">
                  {personaje.descripcion || 'Sin descripción disponible'}
                </p>
              </div>

              {/* Habilidades */}
              {personaje.habilidades && personaje.habilidades.length > 0 && (
                <div className="personaje-info-section">
                  <h5 className="text-success mb-3">⚡ Habilidades</h5>
                  <div className="habilidades-container">
                    {personaje.habilidades.map((habilidad, index) => (
                      <span key={index} className="badge bg-success habilidad-badge">
                        {habilidad}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Botón para volver en móvil */}
      <div className="d-md-none mt-3 text-center">
        <Link to="/personajes" className="btn btn-secondary btn-lg">
          ← Volver a Personajes
        </Link>
      </div>
    </div>
  );
};

export default PersonajeDetail;

// frontend/src/app/components/personajes/personaje-detail/personaje-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { PersonajeService } from '../../../services/personaje.service';
import { SharedService } from '../../../services/shared.service';
import { Personaje } from '../../../models/interfaces';

@Component({
  selector: 'app-personaje-detail',
  standalone: true,
  templateUrl: './personaje-detail.component.html',
  styleUrls: ['./personaje-detail.component.css'],
  imports: [CommonModule, RouterModule]
})
export class PersonajeDetailComponent implements OnInit {
  personaje: Personaje | null = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private personajeService: PersonajeService,
    private sharedService: SharedService
  ) {}

  ngOnInit() {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.cargarPersonaje(id);
    }
  }

  cargarPersonaje(id: string) {
    this.sharedService.showLoading();
    this.personajeService.getById(id).subscribe({
      next: (response) => {
        this.sharedService.hideLoading();
        if (response.success && response.data) {
          this.personaje = response.data;
        }
      },
      error: (error) => {
        this.sharedService.hideLoading();
        this.sharedService.showError('Error al cargar el personaje');
        console.error(error);
        this.router.navigate(['/personajes']);
      }
    });
  }

  editar() {
    if (this.personaje && this.personaje._id) {
      this.router.navigate(['/personajes', 'editar', this.personaje._id]);
    }
  }

  eliminar() {
    if (!this.personaje || !this.personaje._id) return;

    if (confirm(`¿Estás seguro de eliminar a ${this.personaje.nombre}?`)) {
      this.sharedService.showLoading();
      this.personajeService.delete(this.personaje._id).subscribe({
        next: (response) => {
          this.sharedService.hideLoading();
          if (response.success) {
            this.sharedService.showSuccess('Personaje eliminado correctamente');
            this.router.navigate(['/personajes']);
          }
        },
        error: (error) => {
          this.sharedService.hideLoading();
          this.sharedService.showError('Error al eliminar el personaje');
          console.error(error);
        }
      });
    }
  }

  getRolBadgeClass(rol: string): string {
    switch (rol) {
      case 'principal':
        return 'badge bg-primary';
      case 'secundario':
        return 'badge bg-success';
      case 'recurrente':
        return 'badge bg-info';
      default:
        return 'badge bg-secondary';
    }
  }

  volver() {
    this.router.navigate(['/personajes']);
  }
}

<div class="container mt-4" *ngIf="personaje">
  <div class="card">
    <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
      <h3 class="mb-0">👤 {{ personaje.nombre }}</h3>
      <div>
        <button class="btn btn-warning btn-sm me-2" (click)="editar()">
          ✏️ Editar
        </button>
        <button class="btn btn-danger btn-sm me-2" (click)="eliminar()">
          🗑️ Eliminar
        </button>
        <button class="btn btn-secondary btn-sm" (click)="volver()">
          ← Volver
        </button>
      </div>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-6">
          <h5>Información Básica</h5>
          <table class="table table-bordered">
            <tbody>
              <tr>
                <th width="40%">Nombre</th>
                <td>{{ personaje.nombre }}</td>
              </tr>
              <tr>
                <th>Alias</th>
                <td>{{ personaje.alias || 'Sin alias' }}</td>
              </tr>
              <tr>
                <th>Edad</th>
                <td>{{ personaje.edad || 'Desconocida' }}</td>
              </tr>
              <tr>
                <th>Rol</th>
                <td>
                  <span [ngClass]="getRolBadgeClass(personaje.rol)">
                    {{ personaje.rol }}
                  </span>
                </td>
              </tr>
              <tr>
                <th>Organización</th>
                <td>{{ personaje.organizacion || 'Ninguna' }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-md-6">
          <h5>Habilidades</h5>
          <div *ngIf="personaje.habilidades && personaje.habilidades.length > 0">
            <span 
              *ngFor="let habilidad of personaje.habilidades" 
              class="badge bg-secondary me-2 mb-2">
              {{ habilidad }}
            </span>
          </div>
          <div *ngIf="!personaje.habilidades || personaje.habilidades.length === 0">
            <p class="text-muted">Sin habilidades registradas</p>
          </div>
        </div>
      </div>
      
      <hr>
      
      <div class="row">
        <div class="col-12">
          <h5>Descripción</h5>
          <p class="lead">
            {{ personaje.descripcion }}
          </p>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col-md-6">
          <small class="text-muted">
            Creado: {{ personaje.createdAt | date:'dd/MM/yyyy HH:mm' }}
          </small>
        </div>
        <div class="col-md-6 text-end">
          <small class="text-muted">
            Actualizado: {{ personaje.updatedAt | date:'dd/MM/yyyy HH:mm' }}
          </small>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mt-4" *ngIf="!personaje">
  <div class="alert alert-info">
    Cargando información del personaje...
  </div>
</div>
