// frontend/src/app/components/personajes/personaje-list/personaje-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { PersonajeService } from '../../../services/personaje.service';
import { SharedService } from '../../../services/shared.service';
import { Personaje } from '../../../models/interfaces';

@Component({
  selector: 'app-personaje-list',
  standalone: true,
  templateUrl: './personaje-list.component.html',
  styleUrls: ['./personaje-list.component.css'],
  imports: [CommonModule, RouterModule, FormsModule]
})
export class PersonajeListComponent implements OnInit {
  personajes: Personaje[] = [];
  personajesFiltrados: Personaje[] = [];
  searchTerm = '';
  rolFiltro = '';
  
  // Paginación
  currentPage = 1;
  itemsPerPage = 10;
  totalPages = 1;

  // Exponer Math para el template
  Math = Math;

  constructor(
    private personajeService: PersonajeService,
    private sharedService: SharedService,
    private router: Router
  ) {}

  ngOnInit() {
    console.log('🚀 PersonajeListComponent inicializado');
    console.log('📡 PersonajeService:', this.personajeService);
    console.log('🔧 SharedService:', this.sharedService);
    console.log('📊 Estado inicial:', {
      personajes: this.personajes,
      personajesFiltrados: this.personajesFiltrados,
      currentPage: this.currentPage,
      itemsPerPage: this.itemsPerPage
    });
    this.cargarPersonajes();
  }

  cargarPersonajes() {
    console.log('🔍 Cargando personajes...');
    this.sharedService.showLoading();
    this.personajeService.getAll().subscribe({
      next: (response) => {
        console.log('✅ Respuesta recibida:', response);
        this.sharedService.hideLoading();
        if (response.success && response.data) {
          this.personajes = response.data;
          console.log('📊 Total personajes:', this.personajes.length);
          this.aplicarFiltros();
        } else {
          console.error('❌ Respuesta sin éxito o sin datos');
        }
      },
      error: (error) => {
        console.error('❌ Error al cargar personajes:', error);
        this.sharedService.hideLoading();
        this.sharedService.showError('Error al cargar personajes');
        console.error(error);
      }
    });
  }

  aplicarFiltros() {
    console.log('🔍 Aplicando filtros, total personajes:', this.personajes.length);
    let filtered = [...this.personajes];

    // Filtro por término de búsqueda
    if (this.searchTerm) {
      const term = this.searchTerm.toLowerCase();
      filtered = filtered.filter(p => 
        p.nombre.toLowerCase().includes(term) ||
        (p.alias && p.alias.toLowerCase().includes(term)) ||
        p.descripcion.toLowerCase().includes(term)
      );
    }

    // Filtro por rol
    if (this.rolFiltro) {
      filtered = filtered.filter(p => p.rol === this.rolFiltro);
    }

    this.personajesFiltrados = filtered;
    console.log('📋 Personajes filtrados:', this.personajesFiltrados.length);
    this.totalPages = Math.ceil(this.personajesFiltrados.length / this.itemsPerPage);
    this.currentPage = 1;
  }

  get personajesPaginados(): Personaje[] {
    const start = (this.currentPage - 1) * this.itemsPerPage;
    const end = start + this.itemsPerPage;
    const result = this.personajesFiltrados.slice(start, end);
    console.log(`📄 Página ${this.currentPage}: mostrando ${result.length} personajes (${start}-${end} de ${this.personajesFiltrados.length})`);
    return result;
  }

  cambiarPagina(page: number) {
    if (page >= 1 && page <= this.totalPages) {
      this.currentPage = page;
    }
  }

  verDetalle(id: string) {
    this.router.navigate(['/personajes', id]);
  }

  editar(id: string) {
    this.router.navigate(['/personajes', 'editar', id]);
  }

  eliminar(personaje: Personaje) {
    if (!personaje._id) return;

    if (confirm(`¿Estás seguro de eliminar a ${personaje.nombre}?`)) {
      this.sharedService.showLoading();
      this.personajeService.delete(personaje._id).subscribe({
        next: (response) => {
          this.sharedService.hideLoading();
          if (response.success) {
            this.sharedService.showSuccess('Personaje eliminado correctamente');
            this.cargarPersonajes();
          }
        },
        error: (error) => {
          this.sharedService.hideLoading();
          this.sharedService.showError('Error al eliminar personaje');
          console.error(error);
        }
      });
    }
  }

  getRolBadgeClass(rol: string): string {
    switch (rol) {
      case 'principal':
        return 'badge bg-primary';
      case 'secundario':
        return 'badge bg-success';
      case 'recurrente':
        return 'badge bg-info';
      default:
        return 'badge bg-secondary';
    }
  }

  limpiarFiltros() {
    this.searchTerm = '';
    this.rolFiltro = '';
    this.aplicarFiltros();
  }

  getImagenPersonaje(personaje: Personaje): string {
    if (personaje.imagen_url) {
      return personaje.imagen_url;
    }
    const nombreSlug = personaje.nombre.toLowerCase().replace(/\s+/g, '-');
    return `https://picsum.photos/seed/spyxfamily-${nombreSlug}/400/500`;
  }

  onImageError(event: any): void {
    event.target.src = 'https://via.placeholder.com/400x500/6c757d/ffffff?text=Personaje';
  }
}

<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2>👥 Personajes</h2>
    <button class="btn btn-primary" routerLink="/personajes/nuevo">
      <i class="bi bi-plus-lg"></i> Nuevo Personaje
    </button>
  </div>

  <!-- Filtros -->
  <div class="card mb-4">
    <div class="card-body">
      <div class="row g-3">
        <div class="col-md-6">
          <label class="form-label">Buscar</label>
          <input 
            type="text" 
            class="form-control" 
            placeholder="Buscar por nombre, alias o descripción..."
            [(ngModel)]="searchTerm"
            (ngModelChange)="aplicarFiltros()">
        </div>
        <div class="col-md-4">
          <label class="form-label">Filtrar por Rol</label>
          <select 
            class="form-select" 
            [(ngModel)]="rolFiltro"
            (ngModelChange)="aplicarFiltros()">
            <option value="">Todos los roles</option>
            <option value="principal">Principal</option>
            <option value="secundario">Secundario</option>
            <option value="recurrente">Recurrente</option>
          </select>
        </div>
        <div class="col-md-2 d-flex align-items-end">
          <button class="btn btn-secondary w-100" (click)="limpiarFiltros()">
            Limpiar
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Grid de Tarjetas de Personajes -->
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4 mb-4">
    <div class="col" *ngFor="let personaje of personajesPaginados">
      <div class="card h-100">
        <img 
          [src]="getImagenPersonaje(personaje)" 
          class="card-img-top" 
          [alt]="personaje.nombre"
          style="height: 300px; object-fit: cover; cursor: pointer;"
          (error)="onImageError($event)"
          (click)="verDetalle(personaje._id!)">
        <div class="card-body">
          <h5 class="card-title">{{ personaje.nombre }}</h5>
          <p class="text-muted small" *ngIf="personaje.alias"><em>{{ personaje.alias }}</em></p>
          <div class="mb-2">
            <span [ngClass]="getRolBadgeClass(personaje.rol)" class="me-1">
              {{ personaje.rol }}
            </span>
            <span class="badge bg-secondary" *ngIf="personaje.edad">
              {{ personaje.edad }} años
            </span>
          </div>
          <div class="small text-muted mb-2" *ngIf="personaje.organizacion">
            <strong>Organización:</strong> {{ personaje.organizacion }}
          </div>
          <p class="card-text small" style="display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden;">
            {{ personaje.descripcion }}
          </p>
        </div>
        <div class="card-footer bg-transparent">
          <div class="d-flex justify-content-between">
            <button 
              class="btn btn-sm btn-info" 
              (click)="verDetalle(personaje._id!)"
              title="Ver detalle">
              <i class="bi bi-eye"></i>
            </button>
            <button 
              class="btn btn-sm btn-warning" 
              (click)="editar(personaje._id!)"
              title="Editar">
              <i class="bi bi-pencil"></i>
            </button>
            <button 
              class="btn btn-sm btn-danger" 
              (click)="eliminar(personaje)"
              title="Eliminar">
              <i class="bi bi-trash"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
    
    <div class="col-12" *ngIf="personajesPaginados.length === 0">
      <div class="alert alert-info text-center">
        No se encontraron personajes
      </div>
    </div>
  </div>

  <!-- Paginación -->
  <nav *ngIf="totalPages > 1">
    <ul class="pagination justify-content-center">
      <li class="page-item" [class.disabled]="currentPage === 1">
        <button class="page-link" (click)="cambiarPagina(currentPage - 1)">
          Anterior
        </button>
      </li>
      <li 
        class="page-item" 
        *ngFor="let page of [].constructor(totalPages); let i = index"
        [class.active]="currentPage === i + 1">
        <button class="page-link" (click)="cambiarPagina(i + 1)">
          {{ i + 1 }}
        </button>
      </li>
      <li class="page-item" [class.disabled]="currentPage === totalPages">
        <button class="page-link" (click)="cambiarPagina(currentPage + 1)">
          Siguiente
        </button>
      </li>
    </ul>
  </nav>

  <p class="text-center text-muted">
    Mostrando {{ (currentPage - 1) * itemsPerPage + 1 }} - 
    {{ Math.min(currentPage * itemsPerPage, personajesFiltrados.length) }} 
    de {{ personajesFiltrados.length }} personajes
  </p>
</div>

// frontend-react/src/components/personajes/PersonajeList.js
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import personajeService from '../../services/personajeService';
import Loading from '../Loading';

const PersonajeList = () => {
  const [personajes, setPersonajes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [rolFiltro, setRolFiltro] = useState('');

  const getImagenPersonaje = (personaje) => {
    // Si el personaje tiene imagen_url, usarla
    if (personaje.imagen_url) {
      return personaje.imagen_url;
    }
    // Fallback con placeholder
    const nombreSlug = personaje.nombre.toLowerCase().replace(/\s+/g, '-');
    return `https://picsum.photos/seed/spyxfamily-${nombreSlug}/400/500`;
  };

  useEffect(() => {
    cargarPersonajes();
  }, []);

  const cargarPersonajes = async () => {
    try {
      setLoading(true);
      const data = await personajeService.getAll();
      setPersonajes(data);
      setError(null);
    } catch (err) {
      setError('Error al cargar personajes: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id, nombre) => {
    if (window.confirm(`¿Estás seguro de eliminar a "${nombre}"?`)) {
      try {
        await personajeService.delete(id);
        alert('Personaje eliminado correctamente');
        cargarPersonajes();
      } catch (err) {
        alert('Error al eliminar personaje: ' + err.message);
      }
    }
  };

  const personajesFiltrados = personajes.filter((personaje) => {
    const matchSearch =
      searchTerm === '' ||
      personaje.nombre.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (personaje.alias && personaje.alias.toLowerCase().includes(searchTerm.toLowerCase())) ||
      personaje.descripcion.toLowerCase().includes(searchTerm.toLowerCase());
    const matchRol = rolFiltro === '' || personaje.rol === rolFiltro;
    return matchSearch && matchRol;
  });

  if (loading) return <Loading />;

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h2>👥 Personajes</h2>
        <Link to="/personajes/nuevo" className="btn btn-primary">
          <i className="bi bi-plus-lg"></i> Nuevo Personaje
        </Link>
      </div>

      {error && (
        <div className="alert alert-danger alert-dismissible fade show" role="alert">
          {error}
          <button
            type="button"
            className="btn-close"
            onClick={() => setError(null)}
          ></button>
        </div>
      )}

      <div className="card mb-4">
        <div className="card-body">
          <div className="row g-3">
            <div className="col-md-8">
              <label className="form-label">Buscar</label>
              <input
                type="text"
                className="form-control"
                placeholder="Buscar por nombre, alias o descripción..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
            <div className="col-md-4">
              <label className="form-label">Filtrar por Rol</label>
              <select
                className="form-select"
                value={rolFiltro}
                onChange={(e) => setRolFiltro(e.target.value)}
              >
                <option value="">Todos los roles</option>
                <option value="principal">Principal</option>
                <option value="secundario">Secundario</option>
                <option value="recurrente">Recurrente</option>
              </select>
            </div>
          </div>
        </div>
      </div>

      {personajesFiltrados.length === 0 ? (
        <div className="alert alert-info">
          No se encontraron personajes con los filtros seleccionados.
        </div>
      ) : (
        <div className="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4">
          {personajesFiltrados.map((personaje) => (
            <div key={personaje._id} className="col">
              <div className="card h-100">
                <img
                  src={getImagenPersonaje(personaje)}
                  className="card-img-top"
                  alt={personaje.nombre}
                  style={{ height: '300px', objectFit: 'cover' }}
                  onError={(e) => {
                    e.target.src = `https://via.placeholder.com/400x500/667EEA/ffffff?text=${personaje.nombre}`;
                  }}
                />
                <div className="card-body">
                  <h5 className="card-title">{personaje.nombre}</h5>
                  {personaje.alias && (
                    <p className="text-muted small mb-2">
                      <i className="bi bi-shield-check"></i> {personaje.alias}
                    </p>
                  )}
                  <div className="mb-2">
                    <span
                      className={`badge ${
                        personaje.rol === 'principal'
                          ? 'bg-primary'
                          : personaje.rol === 'secundario'
                          ? 'bg-success'
                          : 'bg-info'
                      } me-2`}
                    >
                      {personaje.rol}
                    </span>
                    {personaje.edad && (
                      <span className="badge bg-secondary">
                        {personaje.edad} años
                      </span>
                    )}
                  </div>
                  {personaje.organizacion && (
                    <p className="small text-muted mb-2">
                      <i className="bi bi-building"></i> {personaje.organizacion}
                    </p>
                  )}
                  <p className="card-text small" style={{ 
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    display: '-webkit-box',
                    WebkitLineClamp: 3,
                    WebkitBoxOrient: 'vertical'
                  }}>
                    {personaje.descripcion}
                  </p>
                </div>
                <div className="card-footer bg-white border-top">
                  <div className="d-flex justify-content-between">
                    <Link
                      to={`/personajes/${personaje._id}`}
                      className="btn btn-sm btn-info"
                    >
                      <i className="bi bi-eye"></i> Ver
                    </Link>
                    <Link
                      to={`/personajes/editar/${personaje._id}`}
                      className="btn btn-sm btn-warning"
                    >
                      <i className="bi bi-pencil"></i> Editar
                    </Link>
                    <button
                      className="btn btn-sm btn-danger"
                      onClick={() => handleDelete(personaje._id, personaje.nombre)}
                    >
                      <i className="bi bi-trash"></i>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default PersonajeList;
