// frontend/src/app/components/personajes/personaje-form/personaje-form.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule, FormArray } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { PersonajeService } from '../../../services/personaje.service';
import { SharedService } from '../../../services/shared.service';
import { Personaje } from '../../../models/interfaces';

@Component({
  selector: 'app-personaje-form',
  standalone: true,
  templateUrl: './personaje-form.component.html',
  styleUrls: ['./personaje-form.component.css'],
  imports: [CommonModule, ReactiveFormsModule]
})
export class PersonajeFormComponent implements OnInit {
  personajeForm!: FormGroup;
  isEditMode = false;
  personajeId: string | null = null;
  submitted = false;

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private personajeService: PersonajeService,
    private sharedService: SharedService
  ) {
    this.initForm();
  }

  ngOnInit() {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.isEditMode = true;
      this.personajeId = id;
      this.cargarPersonaje(id);
    }
  }

  initForm() {
    this.personajeForm = this.fb.group({
      nombre: ['', [Validators.required, Validators.minLength(2), Validators.maxLength(100)]],
      alias: [''],
      edad: ['', [Validators.min(0), Validators.max(120)]],
      rol: ['', Validators.required],
      descripcion: ['', [Validators.required, Validators.minLength(10)]],
      habilidades: this.fb.array([]),
      organizacion: ['']
    });
  }

  get habilidades(): FormArray {
    return this.personajeForm.get('habilidades') as FormArray;
  }

  agregarHabilidad() {
    this.habilidades.push(this.fb.control('', Validators.required));
  }

  eliminarHabilidad(index: number) {
    this.habilidades.removeAt(index);
  }

  cargarPersonaje(id: string) {
    this.sharedService.showLoading();
    this.personajeService.getById(id).subscribe({
      next: (response) => {
        this.sharedService.hideLoading();
        if (response.success && response.data) {
          const personaje = response.data;
          
          // Limpiar array de habilidades
          while (this.habilidades.length !== 0) {
            this.habilidades.removeAt(0);
          }
          
          // Agregar habilidades existentes
          if (personaje.habilidades && personaje.habilidades.length > 0) {
            personaje.habilidades.forEach(habilidad => {
              this.habilidades.push(this.fb.control(habilidad, Validators.required));
            });
          }
          
          this.personajeForm.patchValue({
            nombre: personaje.nombre,
            alias: personaje.alias || '',
            edad: personaje.edad || '',
            rol: personaje.rol,
            descripcion: personaje.descripcion,
            organizacion: personaje.organizacion || ''
          });
        }
      },
      error: (error) => {
        this.sharedService.hideLoading();
        this.sharedService.showError('Error al cargar el personaje');
        console.error(error);
        this.router.navigate(['/personajes']);
      }
    });
  }

  onSubmit() {
    this.submitted = true;

    if (this.personajeForm.invalid) {
      this.sharedService.showWarning('Por favor, completa todos los campos requeridos');
      return;
    }

    const personajeData: Personaje = {
      ...this.personajeForm.value,
      alias: this.personajeForm.value.alias || null,
      edad: this.personajeForm.value.edad || null,
      organizacion: this.personajeForm.value.organizacion || null
    };

    this.sharedService.showLoading();

    if (this.isEditMode && this.personajeId) {
      this.personajeService.update(this.personajeId, personajeData).subscribe({
        next: (response) => {
          this.sharedService.hideLoading();
          if (response.success) {
            this.sharedService.showSuccess('Personaje actualizado correctamente');
            this.router.navigate(['/personajes', this.personajeId]);
          }
        },
        error: (error) => {
          this.sharedService.hideLoading();
          this.sharedService.showError(
            error.error?.message || 'Error al actualizar el personaje'
          );
          console.error(error);
        }
      });
    } else {
      this.personajeService.create(personajeData).subscribe({
        next: (response) => {
          this.sharedService.hideLoading();
          if (response.success) {
            this.sharedService.showSuccess('Personaje creado correctamente');
            this.router.navigate(['/personajes']);
          }
        },
        error: (error) => {
          this.sharedService.hideLoading();
          this.sharedService.showError(
            error.error?.message || 'Error al crear el personaje'
          );
          console.error(error);
        }
      });
    }
  }

  get f() { return this.personajeForm.controls; }

  cancelar() {
    this.router.navigate(['/personajes']);
  }
}

<div class="container mt-4">
  <div class="card">
    <div class="card-header bg-primary text-white">
      <h3 class="mb-0">
        {{ isEditMode ? '✏️ Editar Personaje' : '➕ Nuevo Personaje' }}
      </h3>
    </div>
    <div class="card-body">
      <form [formGroup]="personajeForm" (ngSubmit)="onSubmit()">
        <div class="row">
          <!-- Nombre -->
          <div class="col-md-6 mb-3">
            <label for="nombre" class="form-label">Nombre *</label>
            <input 
              type="text" 
              class="form-control" 
              id="nombre"
              formControlName="nombre"
              [class.is-invalid]="submitted && f['nombre'].errors">
            <div class="invalid-feedback" *ngIf="submitted && f['nombre'].errors">
              <div *ngIf="f['nombre'].errors['required']">El nombre es requerido</div>
              <div *ngIf="f['nombre'].errors['minlength']">Mínimo 2 caracteres</div>
              <div *ngIf="f['nombre'].errors['maxlength']">Máximo 100 caracteres</div>
            </div>
          </div>

          <!-- Alias -->
          <div class="col-md-6 mb-3">
            <label for="alias" class="form-label">Alias</label>
            <input 
              type="text" 
              class="form-control" 
              id="alias"
              formControlName="alias">
            <small class="text-muted">Opcional</small>
          </div>

          <!-- Edad -->
          <div class="col-md-6 mb-3">
            <label for="edad" class="form-label">Edad</label>
            <input 
              type="number" 
              class="form-control" 
              id="edad"
              formControlName="edad"
              min="0"
              max="120"
              [class.is-invalid]="submitted && f['edad'].errors">
            <div class="invalid-feedback" *ngIf="submitted && f['edad'].errors">
              <div *ngIf="f['edad'].errors['min']">La edad debe ser mayor o igual a 0</div>
              <div *ngIf="f['edad'].errors['max']">La edad debe ser menor o igual a 120</div>
            </div>
            <small class="text-muted">Opcional</small>
          </div>

          <!-- Rol -->
          <div class="col-md-6 mb-3">
            <label for="rol" class="form-label">Rol *</label>
            <select 
              class="form-select" 
              id="rol"
              formControlName="rol"
              [class.is-invalid]="submitted && f['rol'].errors">
              <option value="">Seleccione un rol</option>
              <option value="principal">Principal</option>
              <option value="secundario">Secundario</option>
              <option value="recurrente">Recurrente</option>
            </select>
            <div class="invalid-feedback" *ngIf="submitted && f['rol'].errors">
              <div *ngIf="f['rol'].errors['required']">El rol es requerido</div>
            </div>
          </div>

          <!-- Organización -->
          <div class="col-md-12 mb-3">
            <label for="organizacion" class="form-label">Organización</label>
            <input 
              type="text" 
              class="form-control" 
              id="organizacion"
              formControlName="organizacion"
              placeholder="Ej: WISE, Garden, SSS...">
            <small class="text-muted">Opcional</small>
          </div>

          <!-- Descripción -->
          <div class="col-md-12 mb-3">
            <label for="descripcion" class="form-label">Descripción *</label>
            <textarea 
              class="form-control" 
              id="descripcion"
              formControlName="descripcion"
              rows="4"
              [class.is-invalid]="submitted && f['descripcion'].errors"></textarea>
            <div class="invalid-feedback" *ngIf="submitted && f['descripcion'].errors">
              <div *ngIf="f['descripcion'].errors['required']">La descripción es requerida</div>
              <div *ngIf="f['descripcion'].errors['minlength']">Mínimo 10 caracteres</div>
            </div>
          </div>

          <!-- Habilidades -->
          <div class="col-md-12 mb-3">
            <label class="form-label">Habilidades</label>
            <div formArrayName="habilidades">
              <div 
                *ngFor="let habilidad of habilidades.controls; let i = index" 
                class="input-group mb-2">
                <input 
                  type="text" 
                  class="form-control" 
                  [formControlName]="i"
                  placeholder="Ej: Espionaje, Combate...">
                <button 
                  type="button" 
                  class="btn btn-danger" 
                  (click)="eliminarHabilidad(i)">
                  🗑️
                </button>
              </div>
            </div>
            <button 
              type="button" 
              class="btn btn-secondary btn-sm" 
              (click)="agregarHabilidad()">
              ➕ Agregar Habilidad
            </button>
          </div>
        </div>

        <hr>

        <div class="d-flex justify-content-end gap-2">
          <button type="button" class="btn btn-secondary" (click)="cancelar()">
            Cancelar
          </button>
          <button type="submit" class="btn btn-primary">
            {{ isEditMode ? '💾 Guardar Cambios' : '✅ Crear Personaje' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

// frontend-react/src/components/personajes/PersonajeForm.js
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import personajeService from '../../services/personajeService';
import Loading from '../Loading';
import './PersonajeForm.css';

const PersonajeForm = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const isEditing = Boolean(id);

  const [loading, setLoading] = useState(isEditing);
  const [errors, setErrors] = useState({});
  const [habilidadInput, setHabilidadInput] = useState('');
  const [formData, setFormData] = useState({
    nombre: '',
    alias: '',
    edad: '',
    rol: 'secundario',
    descripcion: '',
    habilidades: [],
    organizacion: '',
    imagen_url: '',
  });

  useEffect(() => {
    if (isEditing) {
      cargarPersonaje();
    }
  }, [id]);

  const cargarPersonaje = async () => {
    try {
      const personaje = await personajeService.getById(id);
      setFormData({
        nombre: personaje.nombre,
        alias: personaje.alias || '',
        edad: personaje.edad || '',
        rol: personaje.rol,
        descripcion: personaje.descripcion,
        habilidades: personaje.habilidades || [],
        organizacion: personaje.organizacion || '',
        imagen_url: personaje.imagen_url || '',
      });
    } catch (err) {
      alert('Error al cargar personaje: ' + err.message);
      navigate('/personajes');
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
    // Limpiar error del campo cuando el usuario empieza a escribir
    if (errors[name]) {
      setErrors({
        ...errors,
        [name]: '',
      });
    }
  };

  const handleAddHabilidad = () => {
    if (habilidadInput.trim()) {
      setFormData({
        ...formData,
        habilidades: [...formData.habilidades, habilidadInput.trim()],
      });
      setHabilidadInput('');
    }
  };

  const handleRemoveHabilidad = (index) => {
    setFormData({
      ...formData,
      habilidades: formData.habilidades.filter((_, i) => i !== index),
    });
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      handleAddHabilidad();
    }
  };

  const validateForm = () => {
    const newErrors = {};

    if (!formData.nombre || formData.nombre.trim().length < 2) {
      newErrors.nombre = 'El nombre debe tener al menos 2 caracteres';
    }

    if (formData.edad && (formData.edad < 0 || formData.edad > 120)) {
      newErrors.edad = 'La edad debe estar entre 0 y 120 años';
    }

    if (!formData.rol) {
      newErrors.rol = 'El rol es requerido';
    }

    if (!formData.descripcion || formData.descripcion.trim().length < 10) {
      newErrors.descripcion = 'La descripción debe tener al menos 10 caracteres';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    try {
      const dataToSend = {
        ...formData,
        edad: formData.edad ? Number(formData.edad) : null,
        alias: formData.alias || null,
        organizacion: formData.organizacion || null,
        imagen_url: formData.imagen_url || '',
      };

      if (isEditing) {
        await personajeService.update(id, dataToSend);
        alert('Personaje actualizado correctamente');
      } else {
        await personajeService.create(dataToSend);
        alert('Personaje creado correctamente');
      }
      navigate('/personajes');
    } catch (err) {
      alert('Error al guardar personaje: ' + err.message);
    }
  };

  if (loading) return <Loading />;

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h2>{isEditing ? 'Editar Personaje' : 'Nuevo Personaje'}</h2>
        <Link to="/personajes" className="btn btn-secondary">
          Cancelar
        </Link>
      </div>

      <div className="card">
        <div className="card-body">
          <form onSubmit={handleSubmit}>
            <div className="row">
              <div className="col-md-8 mb-3">
                <label className="form-label">Nombre *</label>
                <input
                  type="text"
                  className={`form-control ${errors.nombre ? 'is-invalid' : ''}`}
                  name="nombre"
                  value={formData.nombre}
                  onChange={handleChange}
                  maxLength="100"
                />
                {errors.nombre && (
                  <div className="invalid-feedback">{errors.nombre}</div>
                )}
              </div>

              <div className="col-md-4 mb-3">
                <label className="form-label">Rol *</label>
                <select
                  className={`form-select ${errors.rol ? 'is-invalid' : ''}`}
                  name="rol"
                  value={formData.rol}
                  onChange={handleChange}
                >
                  <option value="principal">Principal</option>
                  <option value="secundario">Secundario</option>
                  <option value="recurrente">Recurrente</option>
                </select>
                {errors.rol && <div className="invalid-feedback">{errors.rol}</div>}
              </div>
            </div>

            <div className="row">
              <div className="col-md-6 mb-3">
                <label className="form-label">Alias</label>
                <input
                  type="text"
                  className="form-control"
                  name="alias"
                  value={formData.alias}
                  onChange={handleChange}
                  maxLength="100"
                  placeholder="Nombre código o apodo"
                />
              </div>

              <div className="col-md-6 mb-3">
                <label className="form-label">Edad</label>
                <input
                  type="number"
                  className={`form-control ${errors.edad ? 'is-invalid' : ''}`}
                  name="edad"
                  value={formData.edad}
                  onChange={handleChange}
                  min="0"
                  max="120"
                  placeholder="Opcional"
                />
                {errors.edad && (
                  <div className="invalid-feedback">{errors.edad}</div>
                )}
              </div>
            </div>

            <div className="mb-3">
              <label className="form-label">Descripción *</label>
              <textarea
                className={`form-control ${errors.descripcion ? 'is-invalid' : ''}`}
                name="descripcion"
                value={formData.descripcion}
                onChange={handleChange}
                rows="4"
                placeholder="Descripción del personaje..."
              ></textarea>
              {errors.descripcion && (
                <div className="invalid-feedback">{errors.descripcion}</div>
              )}
            </div>

            <div className="mb-3">
              <label className="form-label">Organización</label>
              <input
                type="text"
                className="form-control"
                name="organizacion"
                value={formData.organizacion}
                onChange={handleChange}
                maxLength="100"
                placeholder="Ej: WISE, Garden, etc."
              />
            </div>

            <div className="mb-3">
              <label className="form-label">Habilidades</label>
              <div className="input-group mb-2">
                <input
                  type="text"
                  className="form-control"
                  value={habilidadInput}
                  onChange={(e) => setHabilidadInput(e.target.value)}
                  onKeyPress={handleKeyPress}
                  placeholder="Escribe una habilidad y presiona Enter"
                />
                <button
                  className="btn btn-outline-secondary"
                  type="button"
                  onClick={handleAddHabilidad}
                >
                  <i className="bi bi-plus-lg"></i> Agregar
                </button>
              </div>
              {formData.habilidades.length > 0 && (
                <div className="d-flex flex-wrap gap-2">
                  {formData.habilidades.map((habilidad, index) => (
                    <span key={index} className="badge bg-primary d-flex align-items-center gap-2">
                      {habilidad}
                      <button
                        type="button"
                        className="btn-close btn-close-white"
                        style={{ fontSize: '0.6rem' }}
                        onClick={() => handleRemoveHabilidad(index)}
                      ></button>
                    </span>
                  ))}
                </div>
              )}
            </div>

            <div className="mb-3">
              <label className="form-label">URL de Imagen</label>
              <input
                type="url"
                className="form-control"
                name="imagen_url"
                value={formData.imagen_url}
                onChange={handleChange}
                placeholder="https://ejemplo.com/imagen.jpg"
              />
              {formData.imagen_url && (
                <div className="mt-2">
                  <img
                    src={formData.imagen_url}
                    alt="Preview"
                    className="img-thumbnail"
                    style={{ maxHeight: '200px', objectFit: 'cover' }}
                    onError={(e) => {
                      e.target.src = 'https://via.placeholder.com/200x300/6c757d/ffffff?text=Sin+Imagen';
                    }}
                  />
                </div>
              )}
            </div>

            <div className="d-flex gap-2 justify-content-end">
              <Link to="/personajes" className="btn btn-secondary">
                Cancelar
              </Link>
              <button type="submit" className="btn btn-primary">
                {isEditing ? 'Actualizar' : 'Crear'} Personaje
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default PersonajeForm;
