// frontend-react/src/components/temporadas/TemporadaDetail.js
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import temporadaService from '../../services/temporadaService';
import episodioService from '../../services/episodioService';
import Loading from '../Loading';

const TemporadaDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [temporada, setTemporada] = useState(null);
  const [episodios, setEpisodios] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    cargarTemporada();
    cargarEpisodios();
  }, [id]);

  const cargarTemporada = async () => {
    try {
      const data = await temporadaService.getById(id);
      setTemporada(data);
    } catch (err) {
      setError('Error al cargar temporada: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const cargarEpisodios = async () => {
    try {
      const data = await episodioService.getByTemporada(id);
      setEpisodios(data);
    } catch (err) {
      console.error('Error al cargar episodios:', err);
    }
  };

  const handleDelete = async () => {
    if (window.confirm('¿Estás seguro de eliminar esta temporada?')) {
      try {
        await temporadaService.delete(id);
        alert('Temporada eliminada correctamente');
        navigate('/temporadas');
      } catch (err) {
        alert('Error al eliminar temporada: ' + err.message);
      }
    }
  };

  if (loading) return <Loading />;
  if (error) return <div className="alert alert-danger">{error}</div>;
  if (!temporada) return <div className="alert alert-warning">Temporada no encontrada</div>;

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h2>Detalle de Temporada</h2>
        <div>
          <Link to="/temporadas" className="btn btn-secondary me-2">
            Volver
          </Link>
          <Link
            to={`/temporadas/editar/${temporada._id}`}
            className="btn btn-warning me-2"
          >
            Editar
          </Link>
          <button className="btn btn-danger" onClick={handleDelete}>
            Eliminar
          </button>
        </div>
      </div>

      <div className="card mb-4">
        <div className="card-body">
          <h3>{temporada.titulo}</h3>
          <hr />
          <div className="row">
            <div className="col-md-6">
              <p>
                <strong>Número de Temporada:</strong> {temporada.numero_temporada}
              </p>
              <p>
                <strong>Fecha de Estreno:</strong>{' '}
                {new Date(temporada.fecha_estreno).toLocaleDateString('es-ES')}
              </p>
              <p>
                <strong>Fecha de Finalización:</strong>{' '}
                {temporada.fecha_finalizacion
                  ? new Date(temporada.fecha_finalizacion).toLocaleDateString('es-ES')
                  : 'En emisión'}
              </p>
            </div>
            <div className="col-md-6">
              <p>
                <strong>Número de Episodios:</strong> {temporada.numero_episodios}
              </p>
              <p>
                <strong>Estudio de Animación:</strong> {temporada.estudio_animacion}
              </p>
              <p>
                <strong>Estado:</strong>{' '}
                <span
                  className={`badge ${
                    temporada.estado === 'emitida'
                      ? 'bg-success'
                      : temporada.estado === 'en emisión'
                      ? 'bg-primary'
                      : 'bg-warning'
                  }`}
                >
                  {temporada.estado}
                </span>
              </p>
            </div>
          </div>
          <p>
            <strong>Descripción:</strong>
          </p>
          <p>{temporada.descripcion}</p>
        </div>
      </div>

      {episodios.length > 0 && (
        <div className="card">
          <div className="card-header">
            <h5>Episodios ({episodios.length})</h5>
          </div>
          <div className="card-body">
            <div className="table-responsive">
              <table className="table table-hover">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Título</th>
                    <th>Duración</th>
                    <th>Fecha Emisión</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  {episodios.map((episodio) => (
                    <tr key={episodio._id}>
                      <td>{episodio.numero_episodio}</td>
                      <td>{episodio.titulo}</td>
                      <td>{episodio.duracion_minutos} min</td>
                      <td>
                        {new Date(episodio.fecha_emision).toLocaleDateString('es-ES')}
                      </td>
                      <td>
                        <Link
                          to={`/episodios/${episodio._id}`}
                          className="btn btn-sm btn-info"
                        >
                          Ver
                        </Link>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default TemporadaDetail;

// frontend/src/app/components/temporadas/temporada-detail/temporada-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { TemporadaService } from '../../../services/temporada.service';
import { SharedService } from '../../../services/shared.service';
import { Temporada } from '../../../models/interfaces';

@Component({
  selector: 'app-temporada-detail',
  standalone: true,
  templateUrl: './temporada-detail.component.html',
  styleUrls: ['./temporada-detail.component.css'],
  imports: [CommonModule, RouterModule]
})
export class TemporadaDetailComponent implements OnInit {
  temporada: Temporada | null = null;
  temporadaId: string = '';

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private temporadaService: TemporadaService,
    private sharedService: SharedService
  ) {}

  ngOnInit() {
    this.temporadaId = this.route.snapshot.paramMap.get('id') || '';
    if (this.temporadaId) {
      this.cargarTemporada();
    }
  }

  cargarTemporada() {
    console.log('🔍 Cargando temporada ID:', this.temporadaId);
    this.sharedService.showLoading();
    this.temporadaService.getById(this.temporadaId).subscribe({
      next: (response) => {
        console.log('✅ Temporada recibida:', response);
        this.sharedService.hideLoading();
        if (response.success && response.data) {
          this.temporada = response.data;
          console.log('📊 Temporada cargada:', this.temporada);
          console.log('🎬 Episodios incluidos:', this.temporada.episodios?.length || 0);
        }
      },
      error: (error) => {
        console.error('❌ Error al cargar temporada:', error);
        this.sharedService.hideLoading();
        this.sharedService.showError('Error al cargar la temporada');
        console.error(error);
      }
    });
  }

  eliminar() {
    if (!this.temporada?._id) return;

    if (confirm(`¿Estás seguro de eliminar ${this.temporada.titulo}?`)) {
      this.sharedService.showLoading();
      this.temporadaService.delete(this.temporada._id).subscribe({
        next: (response) => {
          this.sharedService.hideLoading();
          if (response.success) {
            this.sharedService.showSuccess('Temporada eliminada correctamente');
            this.router.navigate(['/temporadas']);
          }
        },
        error: (error) => {
          this.sharedService.hideLoading();
          this.sharedService.showError('Error al eliminar temporada');
          console.error(error);
        }
      });
    }
  }

  getEstadoBadgeClass(estado: string): string {
    switch (estado) {
      case 'emitida':
        return 'badge bg-success';
      case 'en emisión':
        return 'badge bg-primary';
      case 'anunciada':
        return 'badge bg-warning';
      default:
        return 'badge bg-secondary';
    }
  }

  volver() {
    this.router.navigate(['/temporadas']);
  }
}

<div class="container mt-4">
  <div class="row" *ngIf="temporada">
    <div class="col-lg-10 offset-lg-1">
      <!-- Card principal de información -->
      <div class="card mb-4">
        <div class="card-header bg-primary text-white">
          <h3 class="mb-0">📺 Temporada {{ temporada.numero_temporada }}: {{ temporada.titulo }}</h3>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <h5 class="text-muted mb-3">Información General</h5>
              <table class="table table-borderless">
                <tbody>
                  <tr>
                    <th style="width: 40%;">Número de Temporada:</th>
                    <td><strong>{{ temporada.numero_temporada }}</strong></td>
                  </tr>
                  <tr>
                    <th>Título:</th>
                    <td>{{ temporada.titulo }}</td>
                  </tr>
                  <tr>
                    <th>Número de Episodios:</th>
                    <td>{{ temporada.numero_episodios }}</td>
                  </tr>
                  <tr>
                    <th>Estudio de Animación:</th>
                    <td>{{ temporada.estudio_animacion }}</td>
                  </tr>
                  <tr>
                    <th>Estado:</th>
                    <td>
                      <span [ngClass]="getEstadoBadgeClass(temporada.estado)">
                        {{ temporada.estado }}
                      </span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="col-md-6">
              <h5 class="text-muted mb-3">Fechas</h5>
              <table class="table table-borderless">
                <tbody>
                  <tr>
                    <th style="width: 40%;">Fecha de Estreno:</th>
                    <td>{{ temporada.fecha_estreno | date:'dd/MM/yyyy' }}</td>
                  </tr>
                  <tr>
                    <th>Fecha de Finalización:</th>
                    <td>{{ temporada.fecha_finalizacion ? (temporada.fecha_finalizacion | date:'dd/MM/yyyy') : 'Por determinar' }}</td>
                  </tr>
                  <tr>
                    <th>Creado:</th>
                    <td>{{ temporada.createdAt | date:'dd/MM/yyyy HH:mm' }}</td>
                  </tr>
                  <tr>
                    <th>Última Actualización:</th>
                    <td>{{ temporada.updatedAt | date:'dd/MM/yyyy HH:mm' }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          
          <hr>
          
          <div class="row">
            <div class="col-12">
              <h5 class="text-muted mb-3">Descripción</h5>
              <p class="lead">{{ temporada.descripcion }}</p>
            </div>
          </div>

          <div class="d-flex gap-2 mt-4">
            <button class="btn btn-secondary" (click)="volver()">
              ← Volver
            </button>
            <button class="btn btn-danger" (click)="eliminar()">
              🗑️ Eliminar
            </button>
          </div>
        </div>
      </div>

      <!-- Card de episodios -->
      <div class="card" *ngIf="temporada.episodios && temporada.episodios.length > 0">
        <div class="card-header bg-info text-white">
          <h4 class="mb-0">🎬 Episodios de la Temporada ({{ temporada.episodios.length }})</h4>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Episodio</th>
                  <th>Título</th>
                  <th>Duración</th>
                  <th>Fecha de Emisión</th>
                  <th>Valoración</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let episodio of temporada.episodios">
                  <td><strong>{{ episodio.numero_episodio }}</strong></td>
                  <td>{{ episodio.titulo }}</td>
                  <td>{{ episodio.duracion_minutos }} min</td>
                  <td>{{ episodio.fecha_emision | date:'dd/MM/yyyy' }}</td>
                  <td>
                    <span *ngIf="episodio.valoracion">⭐ {{ episodio.valoracion }}/10</span>
                    <span *ngIf="!episodio.valoracion" class="text-muted">-</span>
                  </td>
                  <td>
                    <button 
                      class="btn btn-sm btn-info" 
                      [routerLink]="['/episodios', episodio._id]"
                      title="Ver detalle">
                      👁️ Ver
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Mensaje si no hay episodios -->
      <div class="alert alert-warning mt-4" *ngIf="temporada && temporada.episodios && temporada.episodios.length === 0">
        <strong>⚠️ No hay episodios registrados para esta temporada</strong>
      </div>
    </div>
  </div>

  <div class="alert alert-warning mt-4" *ngIf="!temporada">
    <strong>⚠️ Temporada no encontrada</strong>
  </div>
</div>
