// frontend-react/src/components/Home.js
import React from 'react';
import { Link } from 'react-router-dom';
import './Home.css';

const Home = () => {
  return (
    <div className="home-container">
      <div className="hero-section">
        <h1 className="display-4">🕵️ Spy x Family Database</h1>
        <p className="lead">
          Explora el universo de Spy x Family con información completa sobre temporadas,
          episodios, personajes y tomos del manga.
        </p>
        <p className="text-muted">Frontend desarrollado con React + Hooks</p>
      </div>

      <div className="container mt-5">
        <div className="row g-4">
          <div className="col-md-6 col-lg-3">
            <Link to="/temporadas" className="card-link">
              <div className="card text-center shadow-sm card-hover">
                <div className="card-body">
                  <div className="icon-large">📺</div>
                  <h5 className="card-title">Temporadas</h5>
                  <p className="card-text">Explora las temporadas del anime</p>
                </div>
              </div>
            </Link>
          </div>

          <div className="col-md-6 col-lg-3">
            <Link to="/episodios" className="card-link">
              <div className="card text-center shadow-sm card-hover">
                <div className="card-body">
                  <div className="icon-large">🎬</div>
                  <h5 className="card-title">Episodios</h5>
                  <p className="card-text">Descubre todos los episodios</p>
                </div>
              </div>
            </Link>
          </div>

          <div className="col-md-6 col-lg-3">
            <Link to="/personajes" className="card-link">
              <div className="card text-center shadow-sm card-hover">
                <div className="card-body">
                  <div className="icon-large">👥</div>
                  <h5 className="card-title">Personajes</h5>
                  <p className="card-text">Conoce a todos los personajes</p>
                </div>
              </div>
            </Link>
          </div>

          <div className="col-md-6 col-lg-3">
            <Link to="/tomos" className="card-link">
              <div className="card text-center shadow-sm card-hover">
                <div className="card-body">
                  <div className="icon-large">📖</div>
                  <h5 className="card-title">Tomos</h5>
                  <p className="card-text">Explora los tomos del manga</p>
                </div>
              </div>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;

// frontend/src/app/components/home/home.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-home',
  standalone: true,
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  imports: [CommonModule, RouterModule]
})
export class HomeComponent {
  constructor() {}
}

<div class="home-container">
  <!-- Hero Section -->
  <div class="hero-section">
    <div class="hero-content">
      <h1 class="hero-title">🕵️ Spy x Family</h1>
      <p class="hero-subtitle">Base de datos completa de la serie</p>
      <p class="hero-description">
        Explora el universo de Spy x Family con información detallada sobre temporadas, 
        episodios, personajes y tomos del manga.
      </p>
    </div>
    <div class="hero-images">
      <img src="https://cdn.myanimelist.net/images/anime/1441/122795.jpg" 
           alt="Familia Forger - Loid, Yor, Anya y Bond" 
           class="hero-image"
           onerror="this.src='https://static.wikia.nocookie.net/spy-x-family9745/images/e/ea/Spy_x_Family_Anime.png'">
    </div>
  </div>

  <!-- Cards Grid -->
  <div class="container">
    <div class="cards-grid">
      <!-- Card Temporadas -->
      <div class="card-minimal" routerLink="/temporadas">
        <div class="card-image" style="background-image: url('https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=400&h=200&fit=crop');"></div>
        <div class="card-content">
          <div class="card-icon">📺</div>
          <h2 class="card-title">Temporadas</h2>
          <p class="card-description">Explora las temporadas del anime</p>
        </div>
      </div>

      <!-- Card Episodios -->
      <div class="card-minimal" routerLink="/episodios">
        <div class="card-image" style="background-image: url('https://images.unsplash.com/photo-1574267432644-f9f3cf5e4b52?w=400&h=200&fit=crop');"></div>
        <div class="card-content">
          <div class="card-icon">🎬</div>
          <h2 class="card-title">Episodios</h2>
          <p class="card-description">Descubre todos los episodios</p>
        </div>
      </div>

      <!-- Card Personajes -->
      <div class="card-minimal" routerLink="/personajes">
        <div class="card-image" style="background-image: url('https://images.unsplash.com/photo-1542296332-2e4473faf563?w=400&h=200&fit=crop');"></div>
        <div class="card-content">
          <div class="card-icon">👥</div>
          <h2 class="card-title">Personajes</h2>
          <p class="card-description">Conoce a todos los personajes</p>
        </div>
      </div>

      <!-- Card Tomos -->
      <div class="card-minimal" routerLink="/tomos">
        <div class="card-image" style="background-image: url('https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=200&fit=crop');"></div>
        <div class="card-content">
          <div class="card-icon">📖</div>
          <h2 class="card-title">Tomos</h2>
          <p class="card-description">Explora los tomos del manga</p>
        </div>
      </div>
    </div>
  </div>
</div>
