// frontend/src/app/components/temporadas/temporada-form/temporada-form.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { finalize } from 'rxjs/operators';
import { TemporadaService } from '../../../services/temporada.service';
import { SharedService } from '../../../services/shared.service';
import { Temporada } from '../../../models/interfaces';

@Component({
  selector: 'app-temporada-form',
  standalone: true,
  templateUrl: './temporada-form.component.html',
  styleUrls: ['./temporada-form.component.css'],
  imports: [CommonModule, ReactiveFormsModule]
})
export class TemporadaFormComponent implements OnInit {
  temporadaForm!: FormGroup;
  isEditMode = false;
  temporadaId: string | null = null;
  submitted = false;

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private temporadaService: TemporadaService,
    private sharedService: SharedService
  ) {
    this.initForm();
  }

  ngOnInit() {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.isEditMode = true;
      this.temporadaId = id;
      this.cargarTemporada(id);
    }
  }

  initForm() {
    this.temporadaForm = this.fb.group({
      numero_temporada: ['', [Validators.required, Validators.min(1)]],
      titulo: ['', [Validators.required, Validators.minLength(3), Validators.maxLength(200)]],
      descripcion: ['', [Validators.required, Validators.minLength(10)]],
      fecha_estreno: ['', Validators.required],
      fecha_finalizacion: [''],
      numero_episodios: ['', [Validators.required, Validators.min(1)]],
      estudio_animacion: ['', [Validators.required, Validators.minLength(2)]],
      director: [''],
      estado: ['', Validators.required],
      valoracion: ['', [Validators.min(0), Validators.max(10)]],
      imagen_url: ['']
    });
  }

  cargarTemporada(id: string) {
    this.sharedService.showLoading();
    this.temporadaService.getById(id)
      .pipe(finalize(() => this.sharedService.hideLoading()))
      .subscribe({
        next: (response) => {
          if (response.success && response.data) {
            const temporada = response.data;
            
            // Convertir fechas a formato yyyy-MM-dd para input type="date"
            const fechaEstreno = temporada.fecha_estreno ? 
              new Date(temporada.fecha_estreno).toISOString().split('T')[0] : '';
            const fechaFin = temporada.fecha_finalizacion ? 
              new Date(temporada.fecha_finalizacion).toISOString().split('T')[0] : '';
            
            this.temporadaForm.patchValue({
              numero_temporada: temporada.numero_temporada,
              titulo: temporada.titulo,
              descripcion: temporada.descripcion,
              fecha_estreno: fechaEstreno,
              fecha_finalizacion: fechaFin,
              numero_episodios: temporada.numero_episodios,
              estudio_animacion: temporada.estudio_animacion,
              director: temporada.director || '',
              estado: temporada.estado,
              valoracion: temporada.valoracion || '',
              imagen_url: temporada.imagen_url || ''
            });
          }
        },
        error: (error) => {
          this.sharedService.showError('Error al cargar la temporada');
          console.error(error);
          this.router.navigate(['/temporadas']);
        }
      });
  }

  onSubmit() {
    this.submitted = true;

    if (this.temporadaForm.invalid) {
      this.sharedService.showWarning('Por favor, completa todos los campos requeridos');
      return;
    }

    const temporadaData: Partial<Temporada> = {
      ...this.temporadaForm.value,
      fecha_finalizacion: this.temporadaForm.value.fecha_finalizacion || null,
      director: this.temporadaForm.value.director || null,
      valoracion: this.temporadaForm.value.valoracion || null,
      imagen_url: this.temporadaForm.value.imagen_url || null
    };

    this.sharedService.showLoading();

    if (this.isEditMode && this.temporadaId) {
      this.temporadaService.update(this.temporadaId, temporadaData)
        .pipe(finalize(() => this.sharedService.hideLoading()))
        .subscribe({
          next: (response) => {
            if (response.success) {
              this.sharedService.showSuccess('Temporada actualizada correctamente');
              this.router.navigate(['/temporadas']);
            }
          },
          error: (error) => {
            this.sharedService.showError(
              error.error?.message || 'Error al actualizar la temporada'
            );
            console.error(error);
          }
        });
    } else {
      this.temporadaService.create(temporadaData as Temporada)
        .pipe(finalize(() => this.sharedService.hideLoading()))
        .subscribe({
          next: (response) => {
            if (response.success) {
              this.sharedService.showSuccess('Temporada creada correctamente');
              this.router.navigate(['/temporadas']);
            }
          },
          error: (error) => {
            this.sharedService.showError(
              error.error?.message || 'Error al crear la temporada'
            );
            console.error(error);
          }
        });
    }
  }

  get f() { return this.temporadaForm.controls; }

  cancelar() {
    this.router.navigate(['/temporadas']);
  }
}

<div class="container mt-4">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h3 class="mb-0">
            <i class="bi bi-tv"></i>
            {{ isEditMode ? 'Editar Temporada' : 'Nueva Temporada' }}
          </h3>
        </div>
        <div class="card-body">
          <form [formGroup]="temporadaForm" (ngSubmit)="onSubmit()">
            
            <!-- Número de Temporada y Título -->
            <div class="row mb-3">
              <div class="col-md-3">
                <label for="numero_temporada" class="form-label">Número de Temporada *</label>
                <input 
                  type="number" 
                  class="form-control" 
                  id="numero_temporada"
                  formControlName="numero_temporada"
                  [class.is-invalid]="submitted && f['numero_temporada'].errors"
                  min="1">
                <div *ngIf="submitted && f['numero_temporada'].errors" class="invalid-feedback">
                  <div *ngIf="f['numero_temporada'].errors['required']">El número de temporada es requerido</div>
                  <div *ngIf="f['numero_temporada'].errors['min']">Debe ser al menos 1</div>
                </div>
              </div>
              <div class="col-md-9">
                <label for="titulo" class="form-label">Título *</label>
                <input 
                  type="text" 
                  class="form-control" 
                  id="titulo"
                  formControlName="titulo"
                  [class.is-invalid]="submitted && f['titulo'].errors"
                  placeholder="Ej: SPY×FAMILY Season 1">
                <div *ngIf="submitted && f['titulo'].errors" class="invalid-feedback">
                  <div *ngIf="f['titulo'].errors['required']">El título es requerido</div>
                  <div *ngIf="f['titulo'].errors['minlength']">Mínimo 3 caracteres</div>
                </div>
              </div>
            </div>

            <!-- Descripción -->
            <div class="mb-3">
              <label for="descripcion" class="form-label">Descripción *</label>
              <textarea 
                class="form-control" 
                id="descripcion"
                formControlName="descripcion"
                [class.is-invalid]="submitted && f['descripcion'].errors"
                rows="4"
                placeholder="Descripción de la temporada..."></textarea>
              <div *ngIf="submitted && f['descripcion'].errors" class="invalid-feedback">
                <div *ngIf="f['descripcion'].errors['required']">La descripción es requerida</div>
                <div *ngIf="f['descripcion'].errors['minlength']">Mínimo 10 caracteres</div>
              </div>
            </div>

            <!-- Estudio y Director -->
            <div class="row mb-3">
              <div class="col-md-6">
                <label for="estudio_animacion" class="form-label">Estudio de Animación *</label>
                <input 
                  type="text" 
                  class="form-control" 
                  id="estudio_animacion"
                  formControlName="estudio_animacion"
                  [class.is-invalid]="submitted && f['estudio_animacion'].errors"
                  placeholder="Ej: Wit Studio, CloverWorks">
                <div *ngIf="submitted && f['estudio_animacion'].errors" class="invalid-feedback">
                  <div *ngIf="f['estudio_animacion'].errors['required']">El estudio es requerido</div>
                </div>
              </div>
              <div class="col-md-6">
                <label for="director" class="form-label">Director</label>
                <input 
                  type="text" 
                  class="form-control" 
                  id="director"
                  formControlName="director"
                  placeholder="Nombre del director">
              </div>
            </div>

            <!-- Fechas -->
            <div class="row mb-3">
              <div class="col-md-6">
                <label for="fecha_estreno" class="form-label">Fecha de Estreno *</label>
                <input 
                  type="date" 
                  class="form-control" 
                  id="fecha_estreno"
                  formControlName="fecha_estreno"
                  [class.is-invalid]="submitted && f['fecha_estreno'].errors">
                <div *ngIf="submitted && f['fecha_estreno'].errors" class="invalid-feedback">
                  <div *ngIf="f['fecha_estreno'].errors['required']">La fecha de estreno es requerida</div>
                </div>
              </div>
              <div class="col-md-6">
                <label for="fecha_finalizacion" class="form-label">Fecha de Finalización</label>
                <input 
                  type="date" 
                  class="form-control" 
                  id="fecha_finalizacion"
                  formControlName="fecha_finalizacion">
              </div>
            </div>

            <!-- Número de Episodios y Estado -->
            <div class="row mb-3">
              <div class="col-md-4">
                <label for="numero_episodios" class="form-label">Número de Episodios *</label>
                <input 
                  type="number" 
                  class="form-control" 
                  id="numero_episodios"
                  formControlName="numero_episodios"
                  [class.is-invalid]="submitted && f['numero_episodios'].errors"
                  min="1">
                <div *ngIf="submitted && f['numero_episodios'].errors" class="invalid-feedback">
                  <div *ngIf="f['numero_episodios'].errors['required']">El número de episodios es requerido</div>
                  <div *ngIf="f['numero_episodios'].errors['min']">Debe ser al menos 1</div>
                </div>
              </div>
              <div class="col-md-4">
                <label for="estado" class="form-label">Estado *</label>
                <select 
                  class="form-select" 
                  id="estado"
                  formControlName="estado"
                  [class.is-invalid]="submitted && f['estado'].errors">
                  <option value="">Selecciona un estado</option>
                  <option value="emitida">Emitida</option>
                  <option value="en emisión">En emisión</option>
                  <option value="anunciada">Anunciada</option>
                </select>
                <div *ngIf="submitted && f['estado'].errors" class="invalid-feedback">
                  <div *ngIf="f['estado'].errors['required']">El estado es requerido</div>
                </div>
              </div>
              <div class="col-md-4">
                <label for="valoracion" class="form-label">Valoración (0-10)</label>
                <input 
                  type="number" 
                  class="form-control" 
                  id="valoracion"
                  formControlName="valoracion"
                  [class.is-invalid]="submitted && f['valoracion'].errors"
                  min="0"
                  max="10"
                  step="0.1"
                  placeholder="0.0">
                <div *ngIf="submitted && f['valoracion'].errors" class="invalid-feedback">
                  <div *ngIf="f['valoracion'].errors['min']">Mínimo 0</div>
                  <div *ngIf="f['valoracion'].errors['max']">Máximo 10</div>
                </div>
              </div>
            </div>

            <!-- URL de Imagen -->
            <div class="mb-3">
              <label for="imagen_url" class="form-label">URL de Imagen</label>
              <input 
                type="url" 
                class="form-control" 
                id="imagen_url"
                formControlName="imagen_url"
                placeholder="https://ejemplo.com/imagen.jpg">
            </div>

            <!-- Botones -->
            <div class="d-flex justify-content-end gap-2 mt-4">
              <button type="button" class="btn btn-secondary" (click)="cancelar()">
                <i class="bi bi-x-circle"></i> Cancelar
              </button>
              <button type="submit" class="btn btn-primary">
                <i class="bi bi-save"></i>
                {{ isEditMode ? 'Actualizar' : 'Crear' }} Temporada
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

// frontend-react/src/components/temporadas/TemporadaForm.js
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import temporadaService from '../../services/temporadaService';
import Loading from '../Loading';

const TemporadaForm = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const isEditing = Boolean(id);

  const [loading, setLoading] = useState(isEditing);
  const [errors, setErrors] = useState({});
  const [formData, setFormData] = useState({
    numero_temporada: '',
    titulo: '',
    descripcion: '',
    fecha_estreno: '',
    fecha_finalizacion: '',
    numero_episodios: '',
    estudio_animacion: '',
    estado: 'emitida',
  });

  useEffect(() => {
    if (isEditing) {
      cargarTemporada();
    }
  }, [id]);

  const cargarTemporada = async () => {
    try {
      const temporada = await temporadaService.getById(id);
      setFormData({
        numero_temporada: temporada.numero_temporada,
        titulo: temporada.titulo,
        descripcion: temporada.descripcion,
        fecha_estreno: temporada.fecha_estreno.split('T')[0],
        fecha_finalizacion: temporada.fecha_finalizacion
          ? temporada.fecha_finalizacion.split('T')[0]
          : '',
        numero_episodios: temporada.numero_episodios,
        estudio_animacion: temporada.estudio_animacion,
        estado: temporada.estado,
      });
    } catch (err) {
      alert('Error al cargar temporada: ' + err.message);
      navigate('/temporadas');
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
    // Limpiar error del campo cuando el usuario empieza a escribir
    if (errors[name]) {
      setErrors({
        ...errors,
        [name]: '',
      });
    }
  };

  const validateForm = () => {
    const newErrors = {};

    if (!formData.numero_temporada || formData.numero_temporada < 1) {
      newErrors.numero_temporada = 'El número de temporada debe ser mayor a 0';
    }

    if (!formData.titulo || formData.titulo.trim().length < 3) {
      newErrors.titulo = 'El título debe tener al menos 3 caracteres';
    }

    if (!formData.descripcion || formData.descripcion.trim().length < 10) {
      newErrors.descripcion = 'La descripción debe tener al menos 10 caracteres';
    }

    if (!formData.fecha_estreno) {
      newErrors.fecha_estreno = 'La fecha de estreno es requerida';
    }

    if (!formData.numero_episodios || formData.numero_episodios < 1) {
      newErrors.numero_episodios = 'Debe tener al menos 1 episodio';
    }

    if (!formData.estudio_animacion || formData.estudio_animacion.trim().length < 3) {
      newErrors.estudio_animacion = 'El estudio de animación debe tener al menos 3 caracteres';
    }

    if (!formData.estado) {
      newErrors.estado = 'El estado es requerido';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    try {
      const dataToSend = {
        ...formData,
        numero_temporada: Number(formData.numero_temporada),
        numero_episodios: Number(formData.numero_episodios),
        fecha_finalizacion: formData.fecha_finalizacion || null,
      };

      if (isEditing) {
        await temporadaService.update(id, dataToSend);
        alert('Temporada actualizada correctamente');
      } else {
        await temporadaService.create(dataToSend);
        alert('Temporada creada correctamente');
      }
      navigate('/temporadas');
    } catch (err) {
      alert('Error al guardar temporada: ' + err.message);
    }
  };

  if (loading) return <Loading />;

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h2>{isEditing ? 'Editar Temporada' : 'Nueva Temporada'}</h2>
        <Link to="/temporadas" className="btn btn-secondary">
          Cancelar
        </Link>
      </div>

      <div className="card">
        <div className="card-body">
          <form onSubmit={handleSubmit}>
            <div className="row">
              <div className="col-md-6 mb-3">
                <label className="form-label">Número de Temporada *</label>
                <input
                  type="number"
                  className={`form-control ${errors.numero_temporada ? 'is-invalid' : ''}`}
                  name="numero_temporada"
                  value={formData.numero_temporada}
                  onChange={handleChange}
                  min="1"
                />
                {errors.numero_temporada && (
                  <div className="invalid-feedback">{errors.numero_temporada}</div>
                )}
              </div>

              <div className="col-md-6 mb-3">
                <label className="form-label">Estado *</label>
                <select
                  className={`form-select ${errors.estado ? 'is-invalid' : ''}`}
                  name="estado"
                  value={formData.estado}
                  onChange={handleChange}
                >
                  <option value="emitida">Emitida</option>
                  <option value="en emisión">En emisión</option>
                  <option value="anunciada">Anunciada</option>
                </select>
                {errors.estado && <div className="invalid-feedback">{errors.estado}</div>}
              </div>
            </div>

            <div className="mb-3">
              <label className="form-label">Título *</label>
              <input
                type="text"
                className={`form-control ${errors.titulo ? 'is-invalid' : ''}`}
                name="titulo"
                value={formData.titulo}
                onChange={handleChange}
                maxLength="100"
              />
              {errors.titulo && <div className="invalid-feedback">{errors.titulo}</div>}
            </div>

            <div className="mb-3">
              <label className="form-label">Descripción *</label>
              <textarea
                className={`form-control ${errors.descripcion ? 'is-invalid' : ''}`}
                name="descripcion"
                value={formData.descripcion}
                onChange={handleChange}
                rows="4"
              ></textarea>
              {errors.descripcion && (
                <div className="invalid-feedback">{errors.descripcion}</div>
              )}
            </div>

            <div className="row">
              <div className="col-md-6 mb-3">
                <label className="form-label">Fecha de Estreno *</label>
                <input
                  type="date"
                  className={`form-control ${errors.fecha_estreno ? 'is-invalid' : ''}`}
                  name="fecha_estreno"
                  value={formData.fecha_estreno}
                  onChange={handleChange}
                />
                {errors.fecha_estreno && (
                  <div className="invalid-feedback">{errors.fecha_estreno}</div>
                )}
              </div>

              <div className="col-md-6 mb-3">
                <label className="form-label">Fecha de Finalización</label>
                <input
                  type="date"
                  className="form-control"
                  name="fecha_finalizacion"
                  value={formData.fecha_finalizacion}
                  onChange={handleChange}
                />
                <small className="text-muted">Opcional (dejar vacío si está en emisión)</small>
              </div>
            </div>

            <div className="row">
              <div className="col-md-6 mb-3">
                <label className="form-label">Número de Episodios *</label>
                <input
                  type="number"
                  className={`form-control ${errors.numero_episodios ? 'is-invalid' : ''}`}
                  name="numero_episodios"
                  value={formData.numero_episodios}
                  onChange={handleChange}
                  min="1"
                />
                {errors.numero_episodios && (
                  <div className="invalid-feedback">{errors.numero_episodios}</div>
                )}
              </div>

              <div className="col-md-6 mb-3">
                <label className="form-label">Estudio de Animación *</label>
                <input
                  type="text"
                  className={`form-control ${errors.estudio_animacion ? 'is-invalid' : ''}`}
                  name="estudio_animacion"
                  value={formData.estudio_animacion}
                  onChange={handleChange}
                />
                {errors.estudio_animacion && (
                  <div className="invalid-feedback">{errors.estudio_animacion}</div>
                )}
              </div>
            </div>

            <div className="d-flex justify-content-end gap-2">
              <Link to="/temporadas" className="btn btn-secondary">
                Cancelar
              </Link>
              <button type="submit" className="btn btn-primary">
                {isEditing ? 'Actualizar' : 'Crear'} Temporada
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default TemporadaForm;
