// frontend/src/app/components/temporadas/temporada-list/temporada-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { TemporadaService } from '../../../services/temporada.service';
import { SharedService } from '../../../services/shared.service';
import { Temporada } from '../../../models/interfaces';

@Component({
  selector: 'app-temporada-list',
  standalone: true,
  templateUrl: './temporada-list.component.html',
  styleUrls: ['./temporada-list.component.css'],
  imports: [CommonModule, RouterModule, FormsModule]
})
export class TemporadaListComponent implements OnInit {
  temporadas: Temporada[] = [];
  temporadasFiltradas: Temporada[] = [];
  searchTerm = '';
  estadoFiltro = '';
  
  currentPage = 1;
  itemsPerPage = 10;
  totalPages = 1;
  Math = Math;

  constructor(
    private temporadaService: TemporadaService,
    private sharedService: SharedService,
    private router: Router
  ) {}

  ngOnInit() {
    console.log('🚀 TemporadaListComponent inicializado');
    console.log('📡 TemporadaService:', this.temporadaService);
    console.log('🔧 SharedService:', this.sharedService);
    this.cargarTemporadas();
  }

  cargarTemporadas() {
    console.log('🔍 Cargando temporadas...');
    this.sharedService.showLoading();
    this.temporadaService.getAll().subscribe({
      next: (response) => {
        console.log('✅ Respuesta recibida:', response);
        this.sharedService.hideLoading();
        if (response.success && response.data) {
          this.temporadas = response.data;
          console.log('📊 Total temporadas:', this.temporadas.length);
          this.aplicarFiltros();
        } else {
          console.error('❌ Respuesta sin éxito o sin datos');
        }
      },
      error: (error) => {
        console.error('❌ Error al cargar temporadas:', error);
        this.sharedService.hideLoading();
        this.sharedService.showError('Error al cargar temporadas');
        console.error(error);
      }
    });
  }

  aplicarFiltros() {
    console.log('🔍 Aplicando filtros, total temporadas:', this.temporadas.length);
    let filtered = [...this.temporadas];

    if (this.searchTerm) {
      const term = this.searchTerm.toLowerCase();
      filtered = filtered.filter(t => 
        t.titulo.toLowerCase().includes(term) ||
        t.descripcion.toLowerCase().includes(term)
      );
    }

    if (this.estadoFiltro) {
      filtered = filtered.filter(t => t.estado === this.estadoFiltro);
    }

    this.temporadasFiltradas = filtered;
    console.log('📋 Temporadas filtradas:', this.temporadasFiltradas.length);
    this.totalPages = Math.ceil(this.temporadasFiltradas.length / this.itemsPerPage);
    this.currentPage = 1;
  }

  get temporadasPaginadas(): Temporada[] {
    const start = (this.currentPage - 1) * this.itemsPerPage;
    const end = start + this.itemsPerPage;
    const result = this.temporadasFiltradas.slice(start, end);
    console.log(`📄 Página ${this.currentPage}: mostrando ${result.length} temporadas (${start}-${end} de ${this.temporadasFiltradas.length})`);
    return result;
  }

  cambiarPagina(page: number) {
    if (page >= 1 && page <= this.totalPages) {
      this.currentPage = page;
    }
  }

  verDetalle(id: string) {
    this.router.navigate(['/temporadas', id]);
  }

  verEpisodios(temporadaId: string) {
    this.router.navigate(['/episodios'], {
      queryParams: { temporada: temporadaId }
    });
  }

  eliminar(temporada: Temporada) {
    if (!temporada._id) return;

    if (confirm(`¿Estás seguro de eliminar la ${temporada.titulo}?`)) {
      this.sharedService.showLoading();
      this.temporadaService.delete(temporada._id).subscribe({
        next: (response) => {
          this.sharedService.hideLoading();
          if (response.success) {
            this.sharedService.showSuccess('Temporada eliminada correctamente');
            this.cargarTemporadas();
          }
        },
        error: (error) => {
          this.sharedService.hideLoading();
          const mensaje = error.error?.message || 'Error al eliminar temporada';
          this.sharedService.showError(mensaje);
          console.error(error);
        }
      });
    }
  }

  getEstadoBadgeClass(estado: string): string {
    switch (estado) {
      case 'emitida':
        return 'badge bg-success';
      case 'en emisión':
        return 'badge bg-primary';
      case 'anunciada':
        return 'badge bg-warning';
      default:
        return 'badge bg-secondary';
    }
  }

  limpiarFiltros() {
    this.searchTerm = '';
    this.estadoFiltro = '';
    this.aplicarFiltros();
  }

  getImagenTemporada(temporada: Temporada): string {
    if (temporada.imagen_url) {
      return temporada.imagen_url;
    }
    return `https://picsum.photos/seed/spyxfamily-temporada${temporada.numero_temporada}/400/600`;
  }

  onImageError(event: any): void {
    event.target.src = 'https://via.placeholder.com/400x600/6c757d/ffffff?text=Temporada';
  }
}

<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2>📺 Temporadas</h2>
  </div>

  <!-- Filtros -->
  <div class="card mb-4">
    <div class="card-body">
      <div class="row g-3">
        <div class="col-md-6">
          <label class="form-label">Buscar</label>
          <input 
            type="text" 
            class="form-control" 
            placeholder="Buscar por título o descripción..."
            [(ngModel)]="searchTerm"
            (ngModelChange)="aplicarFiltros()">
        </div>
        <div class="col-md-4">
          <label class="form-label">Filtrar por Estado</label>
          <select 
            class="form-select" 
            [(ngModel)]="estadoFiltro"
            (ngModelChange)="aplicarFiltros()">
            <option value="">Todos los estados</option>
            <option value="emitida">Emitida</option>
            <option value="en emisión">En emisión</option>
            <option value="anunciada">Anunciada</option>
          </select>
        </div>
        <div class="col-md-2 d-flex align-items-end">
          <button class="btn btn-secondary w-100" (click)="limpiarFiltros()">
            Limpiar
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Grid de Tarjetas de Temporadas -->
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 mb-4">
    <div class="col" *ngFor="let temporada of temporadasPaginadas">
      <div class="card h-100">
        <img 
          [src]="getImagenTemporada(temporada)" 
          class="card-img-top" 
          [alt]="temporada.titulo"
          style="height: 300px; object-fit: cover; cursor: pointer;"
          (error)="onImageError($event)"
          (click)="verDetalle(temporada._id!)">
        <div class="card-body">
          <h5 class="card-title">{{ temporada.titulo }}</h5>
          <p class="card-text">{{ temporada.descripcion | slice:0:100 }}{{ temporada.descripcion.length > 100 ? '...' : '' }}</p>
          <div class="mb-2">
            <span class="badge bg-secondary me-2">Temporada {{ temporada.numero_temporada }}</span>
            <span [ngClass]="getEstadoBadgeClass(temporada.estado)">
              {{ temporada.estado }}
            </span>
          </div>
          <div class="small text-muted">
            <div><strong>Episodios:</strong> {{ temporada.numero_episodios }}</div>
            <div><strong>Estudio:</strong> {{ temporada.estudio_animacion }}</div>
            <div><strong>Estreno:</strong> {{ temporada.fecha_estreno | date:'dd/MM/yyyy' }}</div>
            <div *ngIf="temporada.valoracion"><strong>⭐ Valoración:</strong> {{ temporada.valoracion }}/10</div>
          </div>
        </div>
        <div class="card-footer bg-transparent">
          <div class="d-flex justify-content-between mb-2">
            <button 
              class="btn btn-sm btn-primary w-100"
              (click)="verEpisodios(temporada._id!)">
              <i class="bi bi-collection-play"></i> Ver Episodios
            </button>
          </div>
          <div class="d-flex justify-content-between">
            <button 
              class="btn btn-sm btn-info" 
              (click)="verDetalle(temporada._id!)"
              title="Ver detalle">
              <i class="bi bi-eye"></i> Ver
            </button>
            <button 
              class="btn btn-sm btn-danger" 
              (click)="eliminar(temporada)"
              title="Eliminar">
              <i class="bi bi-trash"></i> Eliminar
            </button>
          </div>
        </div>
      </div>
    </div>
    
    <div class="col-12" *ngIf="temporadasPaginadas.length === 0">
      <div class="alert alert-info text-center">
        No se encontraron temporadas
      </div>
    </div>
  </div>

  <!-- Paginación -->
  <nav *ngIf="totalPages > 1">
    <ul class="pagination justify-content-center">
      <li class="page-item" [class.disabled]="currentPage === 1">
        <button class="page-link" (click)="cambiarPagina(currentPage - 1)">
          Anterior
        </button>
      </li>
      <li 
        class="page-item" 
        *ngFor="let page of [].constructor(totalPages); let i = index"
        [class.active]="currentPage === i + 1">
        <button class="page-link" (click)="cambiarPagina(i + 1)">
          {{ i + 1 }}
        </button>
      </li>
      <li class="page-item" [class.disabled]="currentPage === totalPages">
        <button class="page-link" (click)="cambiarPagina(currentPage + 1)">
          Siguiente
        </button>
      </li>
    </ul>
  </nav>

  <p class="text-center text-muted" *ngIf="temporadasFiltradas.length > 0">
    Mostrando {{ (currentPage - 1) * itemsPerPage + 1 }} - 
    {{ Math.min(currentPage * itemsPerPage, temporadasFiltradas.length) }} 
    de {{ temporadasFiltradas.length }} temporadas
  </p>
</div>

// frontend-react/src/components/temporadas/TemporadaList.js
import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import temporadaService from '../../services/temporadaService';
import Loading from '../Loading';
import './TemporadaList.css';

const TemporadaList = () => {
  const navigate = useNavigate();
  const [temporadas, setTemporadas] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [estadoFiltro, setEstadoFiltro] = useState('');

  const getImagenTemporada = (temporada) => {
    // Si la temporada tiene imagen_url, usarla
    if (temporada.imagen_url) {
      return temporada.imagen_url;
    }
    // Fallback con placeholder
    return `https://picsum.photos/seed/spyxfamily-temporada${temporada.numero_temporada}/400/600`;
  };

  useEffect(() => {
    cargarTemporadas();
  }, []);

  const cargarTemporadas = async () => {
    try {
      setLoading(true);
      const data = await temporadaService.getAll();
      setTemporadas(data);
      setError(null);
    } catch (err) {
      setError('Error al cargar temporadas: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id, titulo) => {
    if (window.confirm(`¿Estás seguro de eliminar "${titulo}"?`)) {
      try {
        await temporadaService.delete(id);
        alert('Temporada eliminada correctamente');
        cargarTemporadas();
      } catch (err) {
        alert('Error al eliminar temporada: ' + err.message);
      }
    }
  };

  const handleEstadoBadgeClass = (estado) => {
    switch (estado) {
      case 'emitida':
        return 'bg-success';
      case 'en emisión':
        return 'bg-primary';
      case 'anunciada':
        return 'bg-warning';
      default:
        return 'bg-secondary';
    }
  };

  const temporadasFiltradas = temporadas.filter((temporada) => {
    const matchSearch =
      searchTerm === '' ||
      temporada.titulo.toLowerCase().includes(searchTerm.toLowerCase()) ||
      temporada.descripcion.toLowerCase().includes(searchTerm.toLowerCase());
    const matchEstado = estadoFiltro === '' || temporada.estado === estadoFiltro;
    return matchSearch && matchEstado;
  });

  if (loading) return <Loading />;

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h2>📺 Temporadas</h2>
        <Link to="/temporadas/nueva" className="btn btn-primary">
          <i className="bi bi-plus-lg"></i> Nueva Temporada
        </Link>
      </div>

      {error && (
        <div className="alert alert-danger alert-dismissible fade show" role="alert">
          {error}
          <button
            type="button"
            className="btn-close"
            onClick={() => setError(null)}
          ></button>
        </div>
      )}

      <div className="card mb-4">
        <div className="card-body">
          <div className="row g-3">
            <div className="col-md-8">
              <label className="form-label">Buscar</label>
              <input
                type="text"
                className="form-control"
                placeholder="Buscar por título o descripción..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
            <div className="col-md-4">
              <label className="form-label">Filtrar por Estado</label>
              <select
                className="form-select"
                value={estadoFiltro}
                onChange={(e) => setEstadoFiltro(e.target.value)}
              >
                <option value="">Todos los estados</option>
                <option value="emitida">Emitida</option>
                <option value="en emisión">En emisión</option>
                <option value="anunciada">Anunciada</option>
              </select>
            </div>
          </div>
        </div>
      </div>

      {/* Grid de tarjetas */}
      {temporadasFiltradas.length === 0 ? (
        <div className="alert alert-info">
          No se encontraron temporadas con los filtros seleccionados.
        </div>
      ) : (
        <div className="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
          {temporadasFiltradas.map((temporada) => (
            <div key={temporada._id} className="col">
              <div className="card h-100 temporada-card">
                <img
                  src={getImagenTemporada(temporada)}
                  className="card-img-top"
                  alt={temporada.titulo}
                  style={{ height: '400px', objectFit: 'cover' }}
                />
                <div className="card-body">
                  <div className="d-flex justify-content-between align-items-start mb-2">
                    <h5 className="card-title mb-0">
                      Temporada {temporada.numero_temporada}
                    </h5>
                    <span
                      className={`badge ${handleEstadoBadgeClass(
                        temporada.estado
                      )}`}
                    >
                      {temporada.estado}
                    </span>
                  </div>
                  <h6 className="text-muted mb-3">{temporada.titulo}</h6>
                  <p className="card-text text-truncate-3">
                    {temporada.descripcion}
                  </p>
                  <div className="mb-3">
                    <small className="text-muted">
                      <i className="bi bi-calendar3"></i>{' '}
                      {new Date(temporada.fecha_estreno).toLocaleDateString('es-ES')}
                    </small>
                    <br />
                    <small className="text-muted">
                      <i className="bi bi-collection-play"></i> {temporada.numero_episodios} episodios
                    </small>
                    <br />
                    <small className="text-muted">
                      <i className="bi bi-building"></i> {temporada.estudio_animacion}
                    </small>
                  </div>
                </div>
                <div className="card-footer bg-white border-top-0">
                  <div className="d-flex gap-2 mb-2">
                    <button
                      className="btn btn-sm btn-primary w-100"
                      onClick={() => navigate(`/episodios?temporada=${temporada._id}`)}
                    >
                      <i className="bi bi-collection-play"></i> Ver Episodios
                    </button>
                  </div>
                  <div className="d-flex gap-2">
                    <Link
                      to={`/temporadas/${temporada._id}`}
                      className="btn btn-sm btn-info flex-fill"
                    >
                      <i className="bi bi-eye"></i> Ver
                    </Link>
                    <Link
                      to={`/temporadas/editar/${temporada._id}`}
                      className="btn btn-sm btn-warning flex-fill"
                    >
                      <i className="bi bi-pencil"></i> Editar
                    </Link>
                    <button
                      className="btn btn-sm btn-danger flex-fill"
                      onClick={() =>
                        handleDelete(temporada._id, temporada.titulo)
                      }
                    >
                      <i className="bi bi-trash"></i> Eliminar
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default TemporadaList;
