// frontend-react/src/components/tomos/TomoList.js
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import './TomoList.css';
import tomoService from '../../services/tomoService';
import Loading from '../Loading';

const TomoList = () => {
  const navigate = useNavigate();
  const [tomos, setTomos] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');

  useEffect(() => {
    cargarTomos();
  }, []);

  const cargarTomos = async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await tomoService.getAll();
      console.log('Tomos cargados:', data);
      setTomos(data);
    } catch (err) {
      setError('Error al cargar los tomos: ' + err.message);
      console.error('Error:', err);
    } finally {
      setLoading(false);
    }
  };

  const getImagenTomo = (tomo) => {
    if (tomo.imagen_url) {
      return tomo.imagen_url;
    }
    return `https://picsum.photos/seed/spyxfamily-tomo${tomo.numero_tomo}/300/450`;
  };

  const handleImageError = (e) => {
    e.target.src = 'https://via.placeholder.com/300x450/6c757d/ffffff?text=Tomo';
  };

  const filtrarTomos = () => {
    if (!searchTerm) {
      return tomos;
    }
    const term = searchTerm.toLowerCase();
    return tomos.filter(tomo => 
      tomo.titulo.toLowerCase().includes(term) ||
      tomo.isbn.toLowerCase().includes(term) ||
      tomo.editorial.toLowerCase().includes(term) ||
      (tomo.sinopsis && tomo.sinopsis.toLowerCase().includes(term))
    );
  };

  const formatearFecha = (fecha) => {
    const date = new Date(fecha);
    return date.toLocaleDateString('es-ES', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
  };

  if (loading) return <Loading />;

  if (error) {
    return (
      <div className="container mt-4">
        <div className="alert alert-danger" role="alert">
          {error}
        </div>
      </div>
    );
  }

  const tomosFiltrados = filtrarTomos();

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h2>📖 Tomos del Manga SPY×FAMILY</h2>
      </div>

      {/* Filtros */}
      <div className="card mb-4">
        <div className="card-body">
          <div className="row">
            <div className="col-md-10">
              <label className="form-label fw-bold">Buscar:</label>
              <input
                type="text"
                className="form-control"
                placeholder="Buscar por título, ISBN, editorial o sinopsis..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
            <div className="col-md-2 d-flex align-items-end">
              <button 
                className="btn btn-secondary w-100"
                onClick={() => setSearchTerm('')}
              >
                Limpiar
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Resultados */}
      <div className="mb-3">
        <span className="badge bg-primary">
          {tomosFiltrados.length} tomo{tomosFiltrados.length !== 1 ? 's' : ''} encontrado{tomosFiltrados.length !== 1 ? 's' : ''}
        </span>
      </div>

      {/* Grid de tomos */}
      {tomosFiltrados.length === 0 ? (
        <div className="alert alert-info">
          No se encontraron tomos con los filtros seleccionados.
        </div>
      ) : (
        <div className="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-5 g-4 mb-4">
          {tomosFiltrados.map((tomo) => (
            <div key={tomo._id} className="col">
              <div 
                className="card h-100 tomo-card" 
                onClick={() => navigate(`/tomos/${tomo._id}`)}
                style={{ cursor: 'pointer' }}
              >
                <img
                  src={getImagenTomo(tomo)}
                  className="card-img-top"
                  alt={tomo.titulo}
                  style={{ height: '350px', objectFit: 'contain' }}
                  onError={handleImageError}
                />
                <div className="card-body">
                  <span className="badge bg-primary mb-2">Vol. {tomo.numero_tomo}</span>
                  <h6 className="card-title">{tomo.titulo}</h6>
                  <p className="card-text small tomo-sinopsis">
                    {tomo.sinopsis || 'Sin sinopsis disponible'}
                  </p>
                  <div className="small text-muted">
                    <div><strong>ISBN:</strong> <code className="small">{tomo.isbn}</code></div>
                    <div><strong>Publicación:</strong> {formatearFecha(tomo.fecha_publicacion)}</div>
                    <div><strong>Editorial:</strong> {tomo.editorial}</div>
                    <div><strong>Capítulos:</strong> {tomo.numero_capitulos} | <strong>Páginas:</strong> {tomo.paginas}</div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default TomoList;

// frontend/src/app/components/tomos/tomo-list/tomo-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { TomoService } from '../../../services/tomo.service';
import { SharedService } from '../../../services/shared.service';
import { Tomo } from '../../../models/interfaces';

@Component({
  selector: 'app-tomo-list',
  standalone: true,
  templateUrl: './tomo-list.component.html',
  styleUrls: ['./tomo-list.component.css'],
  imports: [CommonModule, RouterModule, FormsModule]
})
export class TomoListComponent implements OnInit {
  tomos: Tomo[] = [];
  tomosFiltrados: Tomo[] = [];
  searchTerm = '';
  
  currentPage = 1;
  itemsPerPage = 10;
  totalPages = 1;
  Math = Math;

  constructor(
    private tomoService: TomoService,
    private sharedService: SharedService,
    private router: Router
  ) {}

  ngOnInit() {
    console.log('🚀 TomoListComponent inicializado');
    this.cargarTomos();
  }

  cargarTomos() {
    console.log('🔍 Cargando tomos...');
    this.sharedService.showLoading();
    this.tomoService.getAll().subscribe({
      next: (response) => {
        console.log('✅ Respuesta recibida:', response);
        this.sharedService.hideLoading();
        if (response.success && response.data) {
          this.tomos = response.data;
          console.log('📊 Total tomos:', this.tomos.length);
          this.aplicarFiltros();
        }
      },
      error: (error) => {
        console.error('❌ Error al cargar tomos:', error);
        this.sharedService.hideLoading();
        this.sharedService.showError('Error al cargar tomos');
        console.error(error);
      }
    });
  }

  aplicarFiltros() {
    let filtered = [...this.tomos];

    if (this.searchTerm) {
      const term = this.searchTerm.toLowerCase();
      filtered = filtered.filter(t => 
        t.titulo.toLowerCase().includes(term) ||
        t.isbn.toLowerCase().includes(term) ||
        t.editorial.toLowerCase().includes(term)
      );
    }

    this.tomosFiltrados = filtered;
    this.totalPages = Math.ceil(this.tomosFiltrados.length / this.itemsPerPage);
    this.currentPage = 1;
  }

  get tomosPaginados(): Tomo[] {
    const start = (this.currentPage - 1) * this.itemsPerPage;
    const end = start + this.itemsPerPage;
    return this.tomosFiltrados.slice(start, end);
  }

  cambiarPagina(page: number) {
    if (page >= 1 && page <= this.totalPages) {
      this.currentPage = page;
    }
  }

  verDetalle(id: string) {
    this.router.navigate(['/tomos', id]);
  }

  eliminar(tomo: Tomo) {
    if (!tomo._id) return;

    if (confirm(`¿Estás seguro de eliminar "${tomo.titulo}"?`)) {
      this.sharedService.showLoading();
      this.tomoService.delete(tomo._id).subscribe({
        next: (response) => {
          this.sharedService.hideLoading();
          if (response.success) {
            this.sharedService.showSuccess('Tomo eliminado correctamente');
            this.cargarTomos();
          }
        },
        error: (error) => {
          this.sharedService.hideLoading();
          this.sharedService.showError('Error al eliminar tomo');
          console.error(error);
        }
      });
    }
  }

  limpiarFiltros() {
    this.searchTerm = '';
    this.aplicarFiltros();
  }

  getImagenTomo(tomo: Tomo): string {
    if (tomo.imagen_url) {
      return tomo.imagen_url;
    }
    return `https://picsum.photos/seed/spyxfamily-tomo${tomo.numero_tomo}/300/450`;
  }

  onImageError(event: any): void {
    event.target.src = 'https://via.placeholder.com/300x450/6c757d/ffffff?text=Tomo';
  }
}

<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2>📖 Tomos del Manga</h2>
  </div>

  <!-- Filtros -->
  <div class="card mb-4">
    <div class="card-body">
      <div class="row g-3">
        <div class="col-md-10">
          <label class="form-label">Buscar</label>
          <input 
            type="text" 
            class="form-control" 
            placeholder="Buscar por título, ISBN o editorial..."
            [(ngModel)]="searchTerm"
            (ngModelChange)="aplicarFiltros()">
        </div>
        <div class="col-md-2 d-flex align-items-end">
          <button class="btn btn-secondary w-100" (click)="limpiarFiltros()">
            Limpiar
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Grid de Tarjetas de Tomos -->
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-5 g-4 mb-4">
    <div class="col" *ngFor="let tomo of tomosPaginados">
      <div class="card h-100">
        <img 
          [src]="getImagenTomo(tomo)" 
          class="card-img-top" 
          [alt]="tomo.titulo"
          style="height: 350px; object-fit: contain; cursor: pointer;"
          (error)="onImageError($event)"
          (click)="verDetalle(tomo._id!)">
        <div class="card-body">
          <span class="badge bg-primary mb-2">Vol. {{ tomo.numero_tomo }}</span>
          <h6 class="card-title">{{ tomo.titulo }}</h6>
          <p class="card-text small" style="display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden;">
            {{ tomo.sinopsis || 'Sin sinopsis disponible' }}
          </p>
          <div class="small text-muted">
            <div><strong>ISBN:</strong> <code class="small">{{ tomo.isbn }}</code></div>
            <div><strong>Publicación:</strong> {{ tomo.fecha_publicacion | date:'dd/MM/yyyy' }}</div>
            <div><strong>Editorial:</strong> {{ tomo.editorial }}</div>
            <div><strong>Capítulos:</strong> {{ tomo.numero_capitulos }} | <strong>Páginas:</strong> {{ tomo.paginas }}</div>
          </div>
        </div>
        <div class="card-footer bg-transparent">
          <div class="d-flex justify-content-between">
            <button 
              class="btn btn-sm btn-info" 
              (click)="verDetalle(tomo._id!)"
                    title="Ver detalle">
              <i class="bi bi-eye"></i> Ver
            </button>
            <button 
              class="btn btn-sm btn-danger" 
              (click)="eliminar(tomo)"
              title="Eliminar">
              <i class="bi bi-trash"></i> Eliminar
            </button>
          </div>
        </div>
      </div>
    </div>
    
    <div class="col-12" *ngIf="tomosPaginados.length === 0">
      <div class="alert alert-info text-center">
        No se encontraron tomos
      </div>
    </div>
  </div>

  <!-- Paginación -->
  <nav *ngIf="totalPages > 1">
    <ul class="pagination justify-content-center">
      <li class="page-item" [class.disabled]="currentPage === 1">
        <button class="page-link" (click)="cambiarPagina(currentPage - 1)">
          Anterior
        </button>
      </li>
      <li 
        class="page-item" 
        *ngFor="let page of [].constructor(totalPages); let i = index"
        [class.active]="currentPage === i + 1">
        <button class="page-link" (click)="cambiarPagina(i + 1)">
          {{ i + 1 }}
        </button>
      </li>
      <li class="page-item" [class.disabled]="currentPage === totalPages">
        <button class="page-link" (click)="cambiarPagina(currentPage + 1)">
          Siguiente
        </button>
      </li>
    </ul>
  </nav>

  <p class="text-center text-muted" *ngIf="tomosFiltrados.length > 0">
    Mostrando {{ (currentPage - 1) * itemsPerPage + 1 }} - 
    {{ Math.min(currentPage * itemsPerPage, tomosFiltrados.length) }} 
    de {{ tomosFiltrados.length }} tomos
  </p>
